In [1]:
import pandas as pd
import os
from pathlib import Path
import re
from datetime import datetime
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import rasterio
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp
from torchmetrics.classification import MulticlassF1Score
from glob import glob
import torch
import random
import torch.nn.functional as F
import numpy as np
import torch.nn as nn

C:\Users\lolke\miniconda3\envs\cosmohack\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
s1_pre_folder = './bs/sentinel1_pre/'
s1_post_folder = './bs/sentinel1_post/'
s2_pre_folder = './bs/sentinel2_pre/'
s2_post_folder = './bs/sentinel2_post/'
aux_folder = './bs/aux/'

ds_metadata = pd.read_csv("./bs/meta.csv")

In [3]:
import rasterio
import numpy as np

idx = 21
s1_pre_prefix = "_Sentinel-1_pre"
s1_post_prefix = "_Sentinel-1_post"
s2_pre_prefix = "_Sentinel-2_pre"
s2_post_prefix = "_Sentinel-2_post"
aux_prefix = "_AUX"
path = aux_folder + ds_metadata.iloc[idx]["chip_id"] + aux_prefix + ".tif"

with rasterio.open(path) as src:
    s1_pre = src.read().astype(np.float32)  # shape: (C, H, W)
    print("shape:", s1_pre.shape, "dtype:", s1_pre.dtype)
    print("min/max:", s1_pre.min(), s1_pre.max())

shape: (3, 512, 512) dtype: float32
min/max: 4.0 141.0

In [4]:
import numpy as np
import rasterio

path = "bs/aux/BS_tr_000003_AUX.tif"  # подставь реальный путь

with rasterio.open(path) as src:
    aux = src.read().astype(np.float32)
    print("shape:", aux.shape, "dtype в файле:", src.dtypes, "nodata:", src.nodata)

for c in range(aux.shape[0]):
    ch = aux[c]
    finite = ch[np.isfinite(ch)]
    n_unique = len(np.unique(finite))
    print(f"\n--- канал {c} ---")
    print(f"min={finite.min():.2f} max={finite.max():.2f} mean={finite.mean():.2f}")
    print(f"n_unique={n_unique}")
    if n_unique <= 20:
        vals, counts = np.unique(finite, return_counts=True)
        print("уникальные значения и их частоты:", dict(zip(vals.tolist(), counts.tolist())))
    else:
        print("перцентили [1,25,50,75,99]:", np.percentile(finite, [1, 25, 50, 75, 99]))

shape: (3, 512, 512) dtype в файле: ('int16', 'int16', 'int16') nodata: None

--- канал 0 ---
min=-13.00 max=4.00 mean=-5.17
n_unique=18
уникальные значения и их частоты: {-13.0: 27532, -12.0: 523, -11.0: 2766, -10.0: 6764, -9.0: 14710, -8.0: 11386, -7.0: 13435, -6.0: 21161, -5.0: 25662, -4.0: 28859, -3.0: 36360, -2.0: 39721, -1.0: 21101, 0.0: 9513, 1.0: 1501, 2.0: 836, 3.0: 312, 4.0: 2}

--- канал 1 ---
min=1.00 max=1.00 mean=1.00
n_unique=1
уникальные значения и их частоты: {1.0: 262144}

--- канал 2 ---
min=20.00 max=90.00 mean=34.33
n_unique=6
уникальные значения и их частоты: {20.0: 104, 30.0: 227218, 40.0: 58, 60.0: 31517, 80.0: 469, 90.0: 2778}

In [89]:
import random
import numpy as np
import rasterio
import torch
from torch.utils.data import Dataset

S2_SCALE = 10000.0
S1_SCALE = 100.0

S1_CLIP_RANGES = {"VV": (-25.0, 0.0), "VH": (-32.5, 0.0)}

S2_BAND_IDX = {
    "B2": 0, "B3": 1, "B4": 2, "B5": 3, "B6": 4,
    "B7": 5, "B8A": 6, "B11": 7, "B12": 8, "SCL": 9,
}

S2_DN_CLIP = (0.0, 10000.0)

SCL_INVALID = {0, 1, 3, 6, 8, 9, 10}

WORLDCOVER_CODES = [10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 100]
CODE_TO_CLASS_IDX = {code: i for i, code in enumerate(WORLDCOVER_CODES)}
N_LANDCOVER_CLASSES = len(WORLDCOVER_CODES)

LANDCOVER_GROUPS = {
    "forest_shrub": {
        "codes": {10, 20, 95},
        "thresholds": (0.10, 0.27, 0.66),
    },
    "grass_moss": {
        "codes": {30, 100},
        "thresholds": (0.062, 0.204, 0.386),
    },
    "cropland": {
        "codes": {40},
        "thresholds": (0.07, 0.17, 0.38),
    },
    "wetland": {
        "codes": {90},
        "thresholds": (0.075, 0.331, 0.677),
    },
}

LANDCOVER_GROUP_NAMES = [
    "forest_shrub",
    "grass_moss",
    "cropland",
    "wetland",
    "other",
]

N_LANDCOVER_GROUPS = len(LANDCOVER_GROUP_NAMES)
FOLDERS = {
    "s1_pre": ("./bs/sentinel1_pre/", "_Sentinel-1_pre"),
    "s1_post": ("./bs/sentinel1_post/", "_Sentinel-1_post"),
    "s2_pre": ("./bs/sentinel2_pre/", "_Sentinel-2_pre"),
    "s2_post": ("./bs/sentinel2_post/", "_Sentinel-2_post"),
    "aux": ("./bs/aux/", "_AUX"),
    "mask": ("./bs/masks/", "_MASK"),  # уточни реальную папку/суффикс маски у себя
}

def make_landcover_dnbr_features(land_cover_raw, dnbr):
    h, w = land_cover_raw.shape

    group_onehot = np.zeros(
        (N_LANDCOVER_GROUPS, h, w),
        dtype=np.float32,
    )

    threshold_distance = np.zeros(
        (3, h, w),
        dtype=np.float32,
    )

    known_group_mask = np.zeros(
        (h, w),
        dtype=bool,
    )

    dnbr_2d = dnbr[0]

    for group_idx, group_name in enumerate(
        LANDCOVER_GROUP_NAMES[:-1]
    ):
        group_info = LANDCOVER_GROUPS[group_name]

        group_codes = list(group_info["codes"])
        group_mask = np.isin(
            land_cover_raw,
            group_codes,
        )

        thresholds = np.array(
            group_info["thresholds"],
            dtype=np.float32,
        )

        group_onehot[group_idx] = group_mask.astype(
            np.float32
        )

        for threshold_idx in range(3):
            threshold_distance[
                threshold_idx,
                group_mask,
            ] = (
                dnbr_2d[group_mask]
                - thresholds[threshold_idx]
            )

        known_group_mask |= group_mask

    other_mask = ~known_group_mask

    group_onehot[-1] = other_mask.astype(
        np.float32
    )

    threshold_distance = np.clip(
        threshold_distance,
        -1.0,
        1.0,
    )

    return group_onehot, threshold_distance

def landcover_group_to_onehot(land_cover_raw):
    h, w = land_cover_raw.shape

    group_onehot = np.zeros(
        (5, h, w),
        dtype=np.float32,
    )

    forest_shrub_mask = np.isin(
        land_cover_raw,
        [10, 20, 95],
    )

    grass_moss_mask = np.isin(
        land_cover_raw,
        [30, 100],
    )

    cropland_mask = np.isin(
        land_cover_raw,
        [40],
    )

    wetland_mask = np.isin(
        land_cover_raw,
        [90],
    )

    other_mask = ~(
        forest_shrub_mask
        | grass_moss_mask
        | cropland_mask
        | wetland_mask
    )

    group_onehot[0] = forest_shrub_mask.astype(
        np.float32
    )

    group_onehot[1] = grass_moss_mask.astype(
        np.float32
    )

    group_onehot[2] = cropland_mask.astype(
        np.float32
    )

    group_onehot[3] = wetland_mask.astype(
        np.float32
    )

    group_onehot[4] = other_mask.astype(
        np.float32
    )

    return group_onehot


def build_path(chip_id, kind):
    folder, suffix = FOLDERS[kind]
    return folder + chip_id + suffix + ".tif"


def load_tif(path):
    with rasterio.open(path) as src:
        return src.read().astype(np.float32)

def load_s2(path):
    with rasterio.open(path) as src:
        arr = src.read().astype(np.float32)
    arr = np.clip(arr, S2_DN_CLIP[0], S2_DN_CLIP[1])
    return arr

def normalize_s1_db_scaled(arr, band_indices={"VV": 0, "VH": 1}, scale=S1_SCALE):
    h, w = arr.shape[1], arr.shape[2]
    out = np.zeros((2, h, w), dtype=np.float32)
    for out_i, band in enumerate(("VV", "VH")):
        src_i = band_indices[band]
        band_db = arr[src_i] / scale
        lo, hi = S1_CLIP_RANGES[band]
        band_db = np.clip(band_db, lo, hi)
        out[out_i] = (band_db - lo) / (hi - lo)
    return out


def process_s1_pair(s1_pre_raw, s1_post_raw):
    return normalize_s1_db_scaled(s1_pre_raw), normalize_s1_db_scaled(s1_post_raw)


def build_valid_mask_scl(scl_pre, scl_post):
    invalid_pre = np.isin(scl_pre, list(SCL_INVALID))
    invalid_post = np.isin(scl_post, list(SCL_INVALID))
    return (~(invalid_pre | invalid_post)).astype(np.float32)


def process_aux_3ch(aux_arr, elevation_range):
    """aux_arr: (3, H, W) -> [dem, slope, land_cover_class]
    Порядок каналов подтверждён через rasterio descriptions: (dem, slope, landcover).
    Никакой маски валидности в AUX нет — валидность определяется только через SCL.
    """
    dem, slope, land_cover = aux_arr
    dem_norm = np.clip(
        (dem - elevation_range[0]) / (elevation_range[1] - elevation_range[0]),
        0, 1
    ).astype(np.float32)
    slope_norm = np.clip(slope / 90.0, 0, 1).astype(np.float32)  # градусы 0-90 -> [0,1]
    return dem_norm[None, ...], slope_norm[None, ...], land_cover.astype(np.int64)

IGNORE_INDEX = 255

class CosmohackDataset(Dataset):
    def __init__(self, df, is_train=False):
        self.df = df.reset_index(drop=True)
        self.is_train = is_train

    def __len__(self):
        return len(self.df)

    def remap_mask(self, mask):
        return mask.astype(np.int64)  # BS-маска уже 0-3 согласно постановке кейса

    def apply_augmentations(self, x, mask):
        if random.random() > 0.5:
            x = np.flip(x, axis=2)
            mask = np.flip(mask, axis=1)
        if random.random() > 0.5:
            x = np.flip(x, axis=1)
            mask = np.flip(mask, axis=0)
        k = random.randint(0, 3)
        if k > 0:
            x = np.rot90(x, k, axes=(1, 2))
            mask = np.rot90(mask, k, axes=(0, 1))
        return np.ascontiguousarray(x), np.ascontiguousarray(mask)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        chip_id = row["chip_id"]
    
        s2_pre = load_s2(build_path(chip_id, "s2_pre")) / S2_SCALE
        s2_post = load_s2(build_path(chip_id, "s2_post")) / S2_SCALE
    
        idx_red = S2_BAND_IDX["B4"]
        idx_nir = S2_BAND_IDX["B8A"]
        idx_swir1 = S2_BAND_IDX["B11"]
        idx_swir2 = S2_BAND_IDX["B12"]
        idx_scl = S2_BAND_IDX["SCL"]
    
        pre_red = s2_pre[idx_red][None, ...]
        pre_nir = s2_pre[idx_nir][None, ...]
        pre_swir1 = s2_pre[idx_swir1][None, ...]
        pre_swir2 = s2_pre[idx_swir2][None, ...]
    
        post_red = s2_post[idx_red][None, ...]
        post_nir = s2_post[idx_nir][None, ...]
        post_swir1 = s2_post[idx_swir1][None, ...]
        post_swir2 = s2_post[idx_swir2][None, ...]
    
        scl_pre = (s2_pre[idx_scl] * S2_SCALE).round()
        scl_post = (s2_post[idx_scl] * S2_SCALE).round()
    
        pre_nbr1 = np.clip((pre_nir - pre_swir1) / (pre_nir + pre_swir1 + 1e-8), -1.0, 1.0,)
    
        post_nbr1 = np.clip((post_nir - post_swir1) / (post_nir + post_swir1 + 1e-8), -1.0, 1.0,)
    
        pre_nbr2 = np.clip((pre_nir - pre_swir2) / (pre_nir + pre_swir2 + 1e-8), -1.0, 1.0,)
    
        post_nbr2 = np.clip((post_nir - post_swir2) / (post_nir + post_swir2 + 1e-8), -1.0, 1.0)
    
        pre_ndvi = np.clip((pre_nir - pre_red) / (pre_nir + pre_red + 1e-8),-1.0, 1.0,)
    
        post_ndvi = np.clip((post_nir - post_red) / (post_nir + post_red + 1e-8),-1.0, 1.0,)
    
        dndvi = np.clip(pre_ndvi - post_ndvi, -2.0, 2.0)
    
        dnbr1 = np.clip(pre_nbr1 - post_nbr1, -2.0, 2.0)
        dnbr2 = np.clip(pre_nbr2 - post_nbr2, -2.0, 2.0)
    
        rdnbr = dnbr1 / (np.sqrt(np.abs(pre_nbr1)) + 1e-8)
        rdnbr = np.clip(rdnbr, -6.0, 6.0) / 6.0
    
        scl_valid_mask = build_valid_mask_scl(scl_pre, scl_post)[None, ...]
    
        s1_pre_raw = load_tif(build_path(chip_id, "s1_pre"))
        s1_post_raw = load_tif(build_path(chip_id, "s1_post"))
    
        pre_norm_s1, post_norm_s1 = process_s1_pair(
            s1_pre_raw,
            s1_post_raw,
        )
    
        aux_raw = load_tif(build_path(chip_id, "aux"))

        land_cover_raw = aux_raw[2].astype(np.int64)
        
        landcover_group_onehot = landcover_group_to_onehot(land_cover_raw)
    
        combined_valid_mask = scl_valid_mask
        x = np.concatenate([
            pre_red,
            pre_nir,
            pre_swir1,
            pre_swir2,
            
            post_red,
            post_nir,
            post_swir1,
            post_swir2,
    
            # dndvi,
            # dnbr1,
            # dnbr2,
            rdnbr,
    
            # pre_norm_s1,
            # post_norm_s1,
    
            # dem_norm,
            # slope_norm,
    
            # land_cover_onehot,
            # combined_valid_mask,
            # threshold_distance,
            # landcover_group_onehot,
        ], axis=0).astype(np.float32)
        mask_path = build_path(chip_id, "mask")
        mask = load_tif(mask_path).astype(np.int64)[0]
        mask = self.remap_mask(mask)
    
        valid_pixels = combined_valid_mask[0] > 0.5
    
        mask[~valid_pixels] = IGNORE_INDEX
    
        optical_channels = slice(0, 10)
    
        x[optical_channels, ~valid_pixels] = 0.0
    
        x = np.nan_to_num(
            x,
            nan=0.0,
            posinf=0.0,
            neginf=0.0,
        ).astype(np.float32)
    
        if self.is_train:
            x, mask = self.apply_augmentations(x, mask)
    
        x_tensor = torch.from_numpy(x).float()
        mask_tensor = torch.from_numpy(mask).long()
    
        return x_tensor, mask_tensor

In [90]:
device = "cuda"

f1_metric = MulticlassF1Score(
    num_classes=4,
    average=None,
    ignore_index=255
).to(device)

In [91]:
class ConvBlock(torch.nn.Module):
    def __init__(self, ch_in, ch_out):
        super().__init__()
        self.conv = nn.Sequential(
                                  nn.Conv2d(ch_in, ch_out,
                                            kernel_size=3, stride=1,
                                            padding=1, bias=True),
                                  nn.BatchNorm2d(ch_out),
                                  nn.ReLU(inplace=True),
                                  nn.Conv2d(ch_out, ch_out,
                                            kernel_size=3, stride=1,
                                            padding=1, bias=True),
                                  nn.BatchNorm2d(ch_out),
                                  nn.ReLU(inplace=True),
        )
        
    def forward(self, x):
        x = self.conv(x)
        return x

In [92]:
class UpConvBlock(torch.nn.Module):
    def __init__(self, ch_in, ch_out):
        super().__init__()
        self.up = nn.Sequential(
                                nn.Upsample(scale_factor=2),
                                nn.Conv2d(ch_in, ch_out,
                                         kernel_size=3,stride=1,
                                         padding=1, bias=True),
                                nn.BatchNorm2d(ch_out),
                                nn.ReLU(inplace=True),
        )
        
    def forward(self, x):
        x = x = self.up(x)
        return x

In [93]:
class AttentionBlock(torch.nn.Module):
    def __init__(self, f_g, f_l, f_int):
        super().__init__()
        
        self.w_g = nn.Sequential(
                                nn.Conv2d(f_g, f_int,
                                         kernel_size=1, stride=1,
                                         padding=0, bias=True),
                                nn.BatchNorm2d(f_int)
        )
        
        self.w_x = nn.Sequential(
                                nn.Conv2d(f_l, f_int,
                                         kernel_size=1, stride=1,
                                         padding=0, bias=True),
                                nn.BatchNorm2d(f_int)
        )
        
        self.psi = nn.Sequential(
                                nn.Conv2d(f_int, 1,
                                         kernel_size=1, stride=1,
                                         padding=0,  bias=True),
                                nn.BatchNorm2d(1),
                                nn.Sigmoid(),
        )
        
        self.relu = nn.ReLU(inplace=True)
        
    def forward(self, g, x):
        g1 = self.w_g(g)
        x1 = self.w_x(x)
        psi = self.relu(g1+x1)
        psi = self.psi(psi)
        
        return psi*x

In [95]:
class AttentionUNet(torch.nn.Module):
    def __init__(self, n_classes=4, in_channel=9, out_channel=4):
        super().__init__() 
        
        self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.conv1 = ConvBlock(ch_in=in_channel, ch_out=64)
        self.conv2 = ConvBlock(ch_in=64, ch_out=128)
        self.conv3 = ConvBlock(ch_in=128, ch_out=256)
        self.conv4 = ConvBlock(ch_in=256, ch_out=512)
        self.conv5 = ConvBlock(ch_in=512, ch_out=1024)
        
        self.up5 = UpConvBlock(ch_in=1024, ch_out=512)
        self.att5 = AttentionBlock(f_g=512, f_l=512, f_int=256)
        self.upconv5 = ConvBlock(ch_in=1024, ch_out=512)
        
        self.up4 = UpConvBlock(ch_in=512, ch_out=256)
        self.att4 = AttentionBlock(f_g=256, f_l=256, f_int=128)
        self.upconv4 = ConvBlock(ch_in=512, ch_out=256)
        
        self.up3 = UpConvBlock(ch_in=256, ch_out=128)
        self.att3 = AttentionBlock(f_g=128, f_l=128, f_int=64)
        self.upconv3 = ConvBlock(ch_in=256, ch_out=128)
        
        self.up2 = UpConvBlock(ch_in=128, ch_out=64)
        self.att2 = AttentionBlock(f_g=64, f_l=64, f_int=32)
        self.upconv2 = ConvBlock(ch_in=128, ch_out=64)
        
        self.conv_1x1 = nn.Conv2d(64, out_channel,
                                  kernel_size=1, stride=1, padding=0)
        
    def forward(self, x):
        # encoder
        x1 = self.conv1(x)
        
        x2 = self.maxpool(x1)
        x2 = self.conv2(x2)
        
        x3 = self.maxpool(x2)
        x3 = self.conv3(x3)
        
        x4 = self.maxpool(x3)
        x4 = self.conv4(x4)
        
        x5 = self.maxpool(x4)
        x5 = self.conv5(x5)
        
        # decoder + concat
        d5 = self.up5(x5)
        x4 = self.att5(g=d5, x=x4)
        d5 = torch.concat((x4, d5), dim=1)
        d5 = self.upconv5(d5)
        
        d4 = self.up4(d5)
        x3 = self.att4(g=d4, x=x3)
        d4 = torch.concat((x3, d4), dim=1)
        d4 = self.upconv4(d4)
        
        d3 = self.up3(d4)
        x2 = self.att3(g=d3, x=x2)
        d3 = torch.concat((x2, d3), dim=1)
        d3 = self.upconv3(d3)
        
        d2 = self.up2(d3)
        x1 = self.att2(g=d2, x=x1)
        d2 = torch.concat((x1, d2), dim=1)
        d2 = self.upconv2(d2)
        
        d1 = self.conv_1x1(d2)
        
        return d1

In [96]:
from typing import Optional, Sequence
from torch import Tensor

class DiceLoss(nn.Module):
    def __init__(self, num_classes, smooth=1e-6, ignore_index=255):
        super().__init__()
        self.num_classes = num_classes
        self.smooth = smooth
        self.ignore_index = ignore_index

    def forward(self, logits, target):
        valid_mask = (target != self.ignore_index)

        safe_target = target.clone()
        safe_target[~valid_mask] = 0  # временно подменяем, чтобы one_hot не упал

        probs = F.softmax(logits, dim=1)
        target_oh = F.one_hot(safe_target, self.num_classes).permute(0, 3, 1, 2).float()

        valid_mask = valid_mask.unsqueeze(1).float()  # [B, 1, H, W]
        probs = probs * valid_mask
        target_oh = target_oh * valid_mask

        dims = (0, 2, 3)
        intersection = torch.sum(probs * target_oh, dims)
        cardinality = torch.sum(probs + target_oh, dims)
        dice = (2. * intersection + self.smooth) / (cardinality + self.smooth)
        return 1 - dice.mean()

class CombinedLoss(nn.Module):
    def __init__(self, class_weights, num_classes, ce_w=0.5, dice_w=0.5, ignore_index=255):
        super().__init__()
        self.ce = nn.CrossEntropyLoss(weight=class_weights, ignore_index=ignore_index)
        self.dice = DiceLoss(num_classes, ignore_index=ignore_index)
        self.ce_w, self.dice_w = ce_w, dice_w

    def forward(self, logits, target):
        return self.ce_w * self.ce(logits, target) + self.dice_w * self.dice(logits, target)

class FocalLoss(nn.Module):
    """ Focal Loss, as described in https://arxiv.org/abs/1708.02002.

    It is essentially an enhancement to cross entropy loss and is
    useful for classification tasks when there is a large class imbalance.
    x is expected to contain raw, unnormalized scores for each class.
    y is expected to contain class labels.

    Shape:
        - x: (batch_size, C) or (batch_size, C, d1, d2, ..., dK), K > 0.
        - y: (batch_size,) or (batch_size, d1, d2, ..., dK), K > 0.
    """

    def __init__(self,
                 alpha: Optional[Tensor] = None,
                 gamma: float = 0.,
                 reduction: str = 'mean',
                 ignore_index: int = -100):
        """Constructor.

        Args:
            alpha (Tensor, optional): Weights for each class. Defaults to None.
            gamma (float, optional): A constant, as described in the paper.
                Defaults to 0.
            reduction (str, optional): 'mean', 'sum' or 'none'.
                Defaults to 'mean'.
            ignore_index (int, optional): class label to ignore.
                Defaults to -100.
        """
        if reduction not in ('mean', 'sum', 'none'):
            raise ValueError(
                'Reduction must be one of: "mean", "sum", "none".')

        super().__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.ignore_index = ignore_index
        self.reduction = reduction

        self.nll_loss = nn.NLLLoss(
            weight=alpha, reduction='none', ignore_index=ignore_index)

    def __repr__(self):
        arg_keys = ['alpha', 'gamma', 'ignore_index', 'reduction']
        arg_vals = [self.__dict__[k] for k in arg_keys]
        arg_strs = [f'{k}={v!r}' for k, v in zip(arg_keys, arg_vals)]
        arg_str = ', '.join(arg_strs)
        return f'{type(self).__name__}({arg_str})'

    def forward(self, x: Tensor, y: Tensor) -> Tensor:
        if x.ndim > 2:
            # (N, C, d1, d2, ..., dK) --> (N * d1 * ... * dK, C)
            c = x.shape[1]
            x = x.permute(0, *range(2, x.ndim), 1).reshape(-1, c)
            # (N, d1, d2, ..., dK) --> (N * d1 * ... * dK,)
            y = y.view(-1)

        unignored_mask = y != self.ignore_index
        y = y[unignored_mask]
        if y.numel() == 0:
            return x.sum() * 0.0
        x = x[unignored_mask]

        # compute weighted cross entropy term: -alpha * log(pt)
        # (alpha is already part of self.nll_loss)
        log_p = F.log_softmax(x, dim=-1)
        ce = self.nll_loss(log_p, y)

        # get true class column from each row
        all_rows = torch.arange(len(x), device=x.device)
        log_pt = log_p[all_rows, y]

        # compute focal term: (1 - pt)^gamma
        pt = log_pt.exp()
        focal_term = (1 - pt)**self.gamma

        # the full loss: -alpha * ((1 - pt)^gamma) * log(pt)
        loss = focal_term * ce

        if self.reduction == 'mean':
            loss = loss.mean()
        elif self.reduction == 'sum':
            loss = loss.sum()

        return loss


def focal_loss(alpha: Optional[Sequence] = None,
               gamma: float = 2,
               reduction: str = 'mean',
               ignore_index: int = 255,
               device='cuda',
               dtype=torch.float32) -> FocalLoss:
    """Factory function for FocalLoss.

    Args:
        alpha (Sequence, optional): Weights for each class. Will be converted
            to a Tensor if not None. Defaults to None.
        gamma (float, optional): A constant, as described in the paper.
            Defaults to 0.
        reduction (str, optional): 'mean', 'sum' or 'none'.
            Defaults to 'mean'.
        ignore_index (int, optional): class label to ignore.
            Defaults to -100.
        device (str, optional): Device to move alpha to. Defaults to 'cpu'.
        dtype (torch.dtype, optional): dtype to cast alpha to.
            Defaults to torch.float32.

    Returns:
        A FocalLoss object
    """
    if alpha is not None:
        if not isinstance(alpha, Tensor):
            alpha = torch.tensor(alpha)
        alpha = alpha.to(device=device, dtype=dtype)

    fl = FocalLoss(
        alpha=alpha,
        gamma=gamma,
        reduction=reduction,
        ignore_index=ignore_index)
    return fl


class OHEM(nn.Module):
    def __init__(
        self,
        keep_ratio=0.4,
        class_weights=None,
        ignore_index=255,
        min_kept=1,
    ):
        super().__init__()

        if not 0.0 < keep_ratio <= 1.0:
            raise ValueError(
                "keep_ratio должен быть в диапазоне (0, 1]."
            )

        self.keep_ratio = keep_ratio
        self.class_weights = class_weights
        self.ignore_index = ignore_index
        self.min_kept = min_kept

    def forward(self, logits, target):
        pixel_loss = F.cross_entropy(
            logits,
            target,
            weight=self.class_weights,
            ignore_index=self.ignore_index,
            reduction="none",
        )

        valid_mask = target != self.ignore_index
        valid_loss = pixel_loss[valid_mask]

        if valid_loss.numel() == 0:
            return logits.sum() * 0.0

        n_valid = valid_loss.numel()

        n_keep = max(
            int(n_valid * self.keep_ratio),
            self.min_kept,
        )

        n_keep = min(
            n_keep,
            n_valid,
        )

        hard_losses, _ = torch.topk(
            valid_loss,
            k=n_keep,
            largest=True,
            sorted=False,
        )

        return hard_losses.mean()

In [101]:
from torch.utils.data import WeightedRandomSampler

def calculate_sample_weights(df):   
    global_class_counts = np.zeros(4, dtype=np.int64)
    chip_stats = []
    
    for _, row in tqdm(df.iterrows(), total=len(df)):
        chip_id = row["chip_id"]
        mask_path = build_path(chip_id, "mask") 
        
        with rasterio.open(mask_path) as src:
            mask = src.read(1)
            
        counts = np.bincount(mask.ravel(), minlength=4)
        global_class_counts += counts
        chip_stats.append(counts)
    
    class_weights = 1.0 / (global_class_counts + 1)
    class_weights = class_weights / np.sum(class_weights)
    
    sample_weights = []
    for counts in chip_stats:
        weight = np.sum(counts * class_weights)
        sample_weights.append(weight)
        
    return sample_weights

def calculate_class_weights(df):
    counts = np.zeros(4, dtype=np.int64)

    for _, row in tqdm(df.iterrows(), total=len(df)):
        chip_id = row["chip_id"]

        mask = load_tif(build_path(chip_id, "mask"))[0].astype(np.int64)

        s2_pre = load_s2(build_path(chip_id, "s2_pre")) / S2_SCALE
        s2_post = load_s2(build_path(chip_id, "s2_post")) / S2_SCALE

        scl_pre = (s2_pre[S2_BAND_IDX["SCL"]] * S2_SCALE).round()
        scl_post = (s2_post[S2_BAND_IDX["SCL"]] * S2_SCALE).round()

        valid = build_valid_mask_scl(scl_pre, scl_post).astype(bool)

        valid_mask_values = mask[valid]
        counts += np.bincount(valid_mask_values, minlength=4)

    weights = counts.sum() / (len(counts) * np.maximum(counts, 1))
    weights = weights / weights.mean()

    return torch.tensor(weights, dtype=torch.float32, device=device)

In [103]:
import pandas as pd

SPLIT_PATH = "bs_temporal_split_train_2019_2023_val_2024.csv"

saved_split = pd.read_csv(SPLIT_PATH)

print("Saved split:")
print(saved_split["split"].value_counts())

meta_with_dates = ds_metadata.copy()

meta_with_dates["date_post_dt"] = pd.to_datetime(meta_with_dates["date_post"], errors="coerce",)

meta_with_dates["year_post"] = meta_with_dates["date_post_dt"].dt.year

train_ids = saved_split.loc[saved_split["split"] == "train_temporal", "chip_id",]

val_ids = saved_split.loc[saved_split["split"] == "val_2024", "chip_id",]

train_temporal_df = meta_with_dates[meta_with_dates["chip_id"].isin(train_ids)].copy().reset_index(drop=True)

val_2024_df = meta_with_dates[meta_with_dates["chip_id"].isin(val_ids)].copy().reset_index(drop=True)

NUM_EPOCHS = 100

Saved split:
split
train_temporal    142
val_2024           82
Name: count, dtype: int64

In [104]:
train_ds = CosmohackDataset(train_temporal_df, is_train=True,)

val_ds = CosmohackDataset(val_2024_df, is_train=False,)

class_weights = calculate_class_weights(train_temporal_df)

train_sample_weights = calculate_sample_weights(train_temporal_df)

sampler = WeightedRandomSampler(weights=train_sample_weights, num_samples=len(train_sample_weights), replacement=True,)

train_loader = DataLoader(train_ds, batch_size=4, sampler=sampler, shuffle=False, num_workers=0, pin_memory=True)

val_loader = DataLoader(val_ds, batch_size=4, shuffle=False, num_workers=0, pin_memory=True,)

print("Train dataset:", len(train_ds))
print("Val dataset:", len(val_ds))
print("Class weights:", class_weights.detach().cpu().numpy())

100%|██████████| 142/142 [00:10<00:00, 14.18it/s]
100%|██████████| 142/142 [00:00<00:00, 245.80it/s]

Train dataset: 142
Val dataset: 82
Class weights: [0.06004139 1.0758559  1.0559716  1.8081311 ]

In [105]:
NUM_CLASSES = 4
IGNORE_INDEX = 255
device = 'cuda'

best_bs_score = -float("inf")
best_miou_target = -float("inf")

amp_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
scaler = torch.amp.GradScaler("cuda", enabled=(amp_dtype == torch.float16))

model = AttentionUNet().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3, momentum=0.9, weight_decay=1e-4, nesterov=True)
criterion = OHEM()
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=NUM_EPOCHS)

for epoch in tqdm(range(NUM_EPOCHS)):
    model.train()
    train_loss = 0.0
    for images, masks in train_loader:
        images, masks = images.to(device, memory_format=torch.channels_last, non_blocking=True), masks.to(device, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        
        with torch.autocast(device_type="cuda", dtype=amp_dtype):
            outputs = model(images)
            loss = criterion(outputs, masks)
        
        if amp_dtype == torch.bfloat16:
            loss.backward()
            optimizer.step()
        else:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        train_loss += loss.detach().item()
            
    model.eval()
    f1_metric.reset()
    val_loss = 0.0
    # IoU классов 0, 1, 2, 3.
    total_intersection = torch.zeros(NUM_CLASSES,device=device,)
    total_union = torch.zeros(NUM_CLASSES,device=device,)
    
    # Метрики бинарной задачи:
    # burn = target > 0
    burn_intersection = torch.tensor(0.0, device=device,)
    burn_union = torch.tensor(0.0, device=device,)
    burn_pred_pixels = torch.tensor(0.0, device=device,)
    burn_target_pixels = torch.tensor(0.0, device=device,)

    valid_pixels_total = torch.tensor(0.0, device=device,)
    
    val_loss = 0.0
    total_intersection = torch.zeros(4, device=device)
    total_union = torch.zeros(4, device=device)
    
    with torch.no_grad():
        for images, masks in val_loader:
            images = images.to(device, memory_format=torch.channels_last, non_blocking=True)
            masks = masks.to(device, non_blocking=True)
            
            with torch.autocast(device_type="cuda", dtype=amp_dtype):
                outputs = model(images)
                val_loss += criterion(outputs, masks).item()
            preds = outputs.argmax(dim=1)
            f1_metric.update(outputs, masks)
            valid = masks != 255
            
            for c in range(NUM_CLASSES):
                pred_c = (preds == c) & valid
                target_c = (masks == c) & valid
                total_intersection[c] += (pred_c & target_c).sum()
                total_union[c] += (pred_c | target_c).sum()
                
            pred_burn = (preds > 0) & valid
            target_burn = (masks > 0) & valid
    
            burn_intersection += (pred_burn & target_burn).sum()
    
            burn_union += (pred_burn | target_burn).sum()
    
            burn_pred_pixels += pred_burn.sum()
            burn_target_pixels += target_burn.sum()

            valid_pixels_total += valid.sum()

    # IoU для классов 0, 1, 2, 3.
    iou_per_class = torch.where(total_union > 0, total_intersection / total_union, torch.full_like(total_union, float("nan")),).cpu().numpy()
    
    # Mean IoU severity-классов: 1, 2, 3.
    miou_severity = np.nanmean(iou_per_class[1:])
    
    # mIoU всех классов, включая фон.
    miou_all = np.nanmean(iou_per_class)
    
    # Бинарный IoU: burn против background.
    iou_burn = (burn_intersection / (burn_union + 1e-7)).item()
    
    # Дополнительная метрика: F1 именно для burned pixels.
    f1_burn = (2.0 * burn_intersection / (burn_pred_pixels + burn_target_pixels + 1e-7)).item()
    
    pred_burn_fraction = (burn_pred_pixels / valid_pixels_total).item()
    target_burn_fraction = (burn_target_pixels / valid_pixels_total).item()
    
    mean_ious = torch.where(total_union > 0, total_intersection / total_union, torch.full_like(total_union, float("nan"))).cpu().numpy()
    miou_target = np.nanmean(mean_ious[1:])
    f1_epoch = f1_metric.compute().cpu().numpy()
    val_loss /= len(val_loader)
    
    # Эта величина лежит в диапазоне [0, 0.65],
    # потому что 0.35 + 0.30 = 0.65.
    bs_score = (0.35 * iou_burn + 0.30 * miou_severity)
    scheduler.step()

    current_lr = optimizer.param_groups[0]["lr"]
    
    print(
        f"\nEpoch {epoch + 1}/{NUM_EPOCHS} | "
        f"LR: {current_lr:.7f}\n"
        f"Train Loss: {train_loss / len(train_loader):.4f} | "
        f"Val Loss: {val_loss:.4f}\n"
        f"IoU per class [0,1,2,3]: "
        f"{np.round(iou_per_class, 4)}\n"
        f"F1 per class [0,1,2,3]:  "
        f"{np.round(f1_epoch, 4)}\n"
        f"IoU burn: {iou_burn:.4f} | "
        f"F1 burn: {f1_burn:.4f}\n"
        f"mIoU all: {miou_all:.4f} | "
        f"mIoU severity [1-3]: {miou_severity:.4f}\n"
        f"Burn fraction: "
        f"pred={pred_burn_fraction:.4f}, "
        f"true={target_burn_fraction:.4f}\n"
        f"BSScore: {bs_score:.4f}"
    )

    if bs_score > best_bs_score:
        best_bs_score = bs_score
        best_miou_target = miou_severity
    
        torch.save(
            {
                "epoch": epoch + 1,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "bs_score": best_bs_score,
                "iou_burn": iou_burn,
                "f1_burn": f1_burn,
                "miou_severity": miou_severity,
                "iou_per_class": iou_per_class,
                "class_weights": class_weights.detach().cpu(),
            },
            "best_temporal_comboloss_sampler_rdnbr_OHEM.pt",
        )
    
        print(
            f"Checkpoint saved: "
            f"BSScore={best_bs_score:.4f} | "
            f"IoU_burn={iou_burn:.4f} | "
            f"mIoU_severity={miou_severity:.4f}"
        )

  0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100 | LR: 0.0009998
Train Loss: 1.2736 | Val Loss: 1.0074
IoU per class [0,1,2,3]: [0.9102 0.     0.0044 0.024 ]
F1 per class [0,1,2,3]:  [0.953  0.     0.0088 0.0469]
IoU burn: 0.0474 | F1 burn: 0.0905
mIoU all: 0.2347 | mIoU severity [1-3]: 0.0095
Burn fraction: pred=0.0059, true=0.0924
BSScore: 0.0194

  1%|          | 1/100 [00:47<1:18:36, 47.64s/it]

Checkpoint saved: BSScore=0.0194 | IoU_burn=0.0474 | mIoU_severity=0.0095

Epoch 2/100 | LR: 0.0009990
Train Loss: 1.0547 | Val Loss: 0.7329
IoU per class [0,1,2,3]: [9.424e-01 3.000e-04 3.424e-01 5.845e-01]
F1 per class [0,1,2,3]:  [9.704e-01 7.000e-04 5.102e-01 7.378e-01]
IoU burn: 0.4932 | F1 burn: 0.6606
mIoU all: 0.4674 | mIoU severity [1-3]: 0.3091
Burn fraction: pred=0.0683, true=0.0924
BSScore: 0.2653

  2%|▏         | 2/100 [01:38<1:21:10, 49.70s/it]

Checkpoint saved: BSScore=0.2653 | IoU_burn=0.4932 | mIoU_severity=0.3091

  3%|▎         | 3/100 [02:26<1:18:58, 48.85s/it]

Epoch 3/100 | LR: 0.0009978
Train Loss: 0.8914 | Val Loss: 0.5978
IoU per class [0,1,2,3]: [0.9427 0.     0.3129 0.5884]
F1 per class [0,1,2,3]:  [0.9705 0.     0.4766 0.7409]
IoU burn: 0.4941 | F1 burn: 0.6614
mIoU all: 0.4610 | mIoU severity [1-3]: 0.3004
Burn fraction: pred=0.0679, true=0.0924
BSScore: 0.2631

Epoch 4/100 | LR: 0.0009961
Train Loss: 0.8290 | Val Loss: 0.5835
IoU per class [0,1,2,3]: [0.9441 0.     0.3024 0.6032]
F1 per class [0,1,2,3]:  [0.9712 0.     0.4643 0.7525]
IoU burn: 0.5076 | F1 burn: 0.6734
mIoU all: 0.4624 | mIoU severity [1-3]: 0.3019
Burn fraction: pred=0.0694, true=0.0924
BSScore: 0.2682

  4%|▍         | 4/100 [03:15<1:17:59, 48.75s/it]

Checkpoint saved: BSScore=0.2682 | IoU_burn=0.5076 | mIoU_severity=0.3019

  5%|▌         | 5/100 [04:02<1:16:23, 48.25s/it]

Epoch 5/100 | LR: 0.0009938
Train Loss: 0.8981 | Val Loss: 0.5538
IoU per class [0,1,2,3]: [0.942  0.0014 0.3179 0.6427]
F1 per class [0,1,2,3]:  [0.9701 0.0028 0.4825 0.7825]
IoU burn: 0.4621 | F1 burn: 0.6321
mIoU all: 0.4760 | mIoU severity [1-3]: 0.3207
Burn fraction: pred=0.0578, true=0.0924
BSScore: 0.2579

Epoch 6/100 | LR: 0.0009911
Train Loss: 0.8089 | Val Loss: 0.5492
IoU per class [0,1,2,3]: [0.945  0.0255 0.3802 0.5943]
F1 per class [0,1,2,3]:  [0.9717 0.0497 0.551  0.7456]
IoU burn: 0.5318 | F1 burn: 0.6944
mIoU all: 0.4863 | mIoU severity [1-3]: 0.3334
Burn fraction: pred=0.0771, true=0.0924
BSScore: 0.2861

  6%|▌         | 6/100 [04:49<1:15:07, 47.96s/it]

Checkpoint saved: BSScore=0.2861 | IoU_burn=0.5318 | mIoU_severity=0.3334

  7%|▋         | 7/100 [05:36<1:13:30, 47.42s/it]

Epoch 7/100 | LR: 0.0009880
Train Loss: 0.8072 | Val Loss: 0.5084
IoU per class [0,1,2,3]: [0.9395 0.0099 0.2437 0.6505]
F1 per class [0,1,2,3]:  [0.9688 0.0197 0.3919 0.7882]
IoU burn: 0.4267 | F1 burn: 0.5982
mIoU all: 0.4609 | mIoU severity [1-3]: 0.3014
Burn fraction: pred=0.0516, true=0.0924
BSScore: 0.2398

  8%|▊         | 8/100 [06:22<1:12:14, 47.12s/it]

Epoch 8/100 | LR: 0.0009843
Train Loss: 0.7636 | Val Loss: 0.4977
IoU per class [0,1,2,3]: [0.9418 0.0151 0.36   0.5747]
F1 per class [0,1,2,3]:  [0.97   0.0297 0.5294 0.7299]
IoU burn: 0.4510 | F1 burn: 0.6217
mIoU all: 0.4729 | mIoU severity [1-3]: 0.3166
Burn fraction: pred=0.0544, true=0.0924
BSScore: 0.2528

  9%|▉         | 9/100 [07:09<1:11:03, 46.85s/it]

Epoch 9/100 | LR: 0.0009801
Train Loss: 0.7730 | Val Loss: 0.4861
IoU per class [0,1,2,3]: [0.9443 0.0364 0.3636 0.6534]
F1 per class [0,1,2,3]:  [0.9713 0.0702 0.5333 0.7903]
IoU burn: 0.4988 | F1 burn: 0.6656
mIoU all: 0.4994 | mIoU severity [1-3]: 0.3511
Burn fraction: pred=0.0655, true=0.0924
BSScore: 0.2799

Epoch 10/100 | LR: 0.0009755
Train Loss: 0.7804 | Val Loss: 0.5347
IoU per class [0,1,2,3]: [0.947  0.0799 0.3474 0.6448]
F1 per class [0,1,2,3]:  [0.9728 0.148  0.5157 0.784 ]
IoU burn: 0.5609 | F1 burn: 0.7187
mIoU all: 0.5048 | mIoU severity [1-3]: 0.3574
Burn fraction: pred=0.0841, true=0.0924
BSScore: 0.3035

 10%|█         | 10/100 [07:55<1:10:09, 46.78s/it]

Checkpoint saved: BSScore=0.3035 | IoU_burn=0.5609 | mIoU_severity=0.3574

 11%|█         | 11/100 [08:41<1:09:06, 46.59s/it]

Epoch 11/100 | LR: 0.0009704
Train Loss: 0.7524 | Val Loss: 0.4902
IoU per class [0,1,2,3]: [0.9444 0.0443 0.3669 0.703 ]
F1 per class [0,1,2,3]:  [0.9714 0.0848 0.5368 0.8256]
IoU burn: 0.4816 | F1 burn: 0.6501
mIoU all: 0.5146 | mIoU severity [1-3]: 0.3714
Burn fraction: pred=0.0588, true=0.0924
BSScore: 0.2800

 12%|█▏        | 12/100 [09:28<1:08:12, 46.51s/it]

Epoch 12/100 | LR: 0.0009649
Train Loss: 0.7797 | Val Loss: 0.4869
IoU per class [0,1,2,3]: [0.9415 0.0719 0.3563 0.6241]
F1 per class [0,1,2,3]:  [0.9699 0.1342 0.5254 0.7685]
IoU burn: 0.4687 | F1 burn: 0.6383
mIoU all: 0.4985 | mIoU severity [1-3]: 0.3508
Burn fraction: pred=0.0613, true=0.0924
BSScore: 0.2693

Epoch 13/100 | LR: 0.0009589
Train Loss: 0.6967 | Val Loss: 0.5388
IoU per class [0,1,2,3]: [0.9431 0.1973 0.2808 0.5914]
F1 per class [0,1,2,3]:  [0.9707 0.3295 0.4385 0.7433]
IoU burn: 0.5645 | F1 burn: 0.7216
mIoU all: 0.5031 | mIoU severity [1-3]: 0.3565
Burn fraction: pred=0.0981, true=0.0924
BSScore: 0.3045

 13%|█▎        | 13/100 [10:14<1:07:29, 46.55s/it]

Checkpoint saved: BSScore=0.3045 | IoU_burn=0.5645 | mIoU_severity=0.3565

 14%|█▍        | 14/100 [11:01<1:06:46, 46.59s/it]

Epoch 14/100 | LR: 0.0009524
Train Loss: 0.7669 | Val Loss: 0.5074
IoU per class [0,1,2,3]: [0.9407 0.1335 0.4031 0.6744]
F1 per class [0,1,2,3]:  [0.9694 0.2355 0.5746 0.8055]
IoU burn: 0.5051 | F1 burn: 0.6712
mIoU all: 0.5379 | mIoU severity [1-3]: 0.4036
Burn fraction: pred=0.0777, true=0.0924
BSScore: 0.2979

 15%|█▌        | 15/100 [11:47<1:05:51, 46.48s/it]

Epoch 15/100 | LR: 0.0009455
Train Loss: 0.7323 | Val Loss: 0.4894
IoU per class [0,1,2,3]: [0.9459 0.0537 0.3471 0.6582]
F1 per class [0,1,2,3]:  [0.9722 0.102  0.5153 0.7939]
IoU burn: 0.5016 | F1 burn: 0.6681
mIoU all: 0.5012 | mIoU severity [1-3]: 0.3530
Burn fraction: pred=0.0622, true=0.0924
BSScore: 0.2815

Epoch 16/100 | LR: 0.0009382
Train Loss: 0.7339 | Val Loss: 0.4708
IoU per class [0,1,2,3]: [0.9459 0.2149 0.4307 0.6266]
F1 per class [0,1,2,3]:  [0.9722 0.3537 0.6021 0.7704]
IoU burn: 0.5594 | F1 burn: 0.7175
mIoU all: 0.5545 | mIoU severity [1-3]: 0.4241
Burn fraction: pred=0.0867, true=0.0924
BSScore: 0.3230

 16%|█▌        | 16/100 [12:34<1:05:07, 46.52s/it]

Checkpoint saved: BSScore=0.3230 | IoU_burn=0.5594 | mIoU_severity=0.4241

 17%|█▋        | 17/100 [13:20<1:04:09, 46.38s/it]

Epoch 17/100 | LR: 0.0009304
Train Loss: 0.6785 | Val Loss: 0.4360
IoU per class [0,1,2,3]: [0.9437 0.1162 0.3907 0.6498]
F1 per class [0,1,2,3]:  [0.971  0.2082 0.5618 0.7877]
IoU burn: 0.4799 | F1 burn: 0.6485
mIoU all: 0.5251 | mIoU severity [1-3]: 0.3856
Burn fraction: pred=0.0599, true=0.0924
BSScore: 0.2836

 18%|█▊        | 18/100 [14:06<1:03:15, 46.29s/it]

Epoch 18/100 | LR: 0.0009222
Train Loss: 0.7330 | Val Loss: 0.5357
IoU per class [0,1,2,3]: [0.9324 0.1006 0.399  0.7107]
F1 per class [0,1,2,3]:  [0.965  0.1829 0.5704 0.8309]
IoU burn: 0.5020 | F1 burn: 0.6684
mIoU all: 0.5357 | mIoU severity [1-3]: 0.4035
Burn fraction: pred=0.0985, true=0.0924
BSScore: 0.2967

 19%|█▉        | 19/100 [14:52<1:02:23, 46.22s/it]

Epoch 19/100 | LR: 0.0009135
Train Loss: 0.6779 | Val Loss: 0.5455
IoU per class [0,1,2,3]: [0.9359 0.1848 0.4286 0.6471]
F1 per class [0,1,2,3]:  [0.9669 0.312  0.6    0.7857]
IoU burn: 0.5429 | F1 burn: 0.7037
mIoU all: 0.5491 | mIoU severity [1-3]: 0.4202
Burn fraction: pred=0.1088, true=0.0924
BSScore: 0.3161

 20%|██        | 20/100 [15:38<1:01:38, 46.24s/it]

Epoch 20/100 | LR: 0.0009045
Train Loss: 0.6966 | Val Loss: 0.5282
IoU per class [0,1,2,3]: [0.9359 0.022  0.204  0.5601]
F1 per class [0,1,2,3]:  [0.9669 0.0431 0.3388 0.718 ]
IoU burn: 0.3540 | F1 burn: 0.5228
mIoU all: 0.4305 | mIoU severity [1-3]: 0.2620
Burn fraction: pred=0.0373, true=0.0924
BSScore: 0.2025

 21%|██        | 21/100 [16:25<1:01:05, 46.40s/it]

Epoch 21/100 | LR: 0.0008951
Train Loss: 0.6819 | Val Loss: 0.4524
IoU per class [0,1,2,3]: [0.9438 0.1501 0.3751 0.6375]
F1 per class [0,1,2,3]:  [0.9711 0.261  0.5456 0.7786]
IoU burn: 0.4828 | F1 burn: 0.6512
mIoU all: 0.5266 | mIoU severity [1-3]: 0.3876
Burn fraction: pred=0.0608, true=0.0924
BSScore: 0.2853

 22%|██▏       | 22/100 [17:11<1:00:20, 46.41s/it]

Epoch 22/100 | LR: 0.0008853
Train Loss: 0.6528 | Val Loss: 0.4656
IoU per class [0,1,2,3]: [0.9413 0.0795 0.3278 0.5227]
F1 per class [0,1,2,3]:  [0.9698 0.1474 0.4938 0.6866]
IoU burn: 0.4270 | F1 burn: 0.5984
mIoU all: 0.4678 | mIoU severity [1-3]: 0.3100
Burn fraction: pred=0.0477, true=0.0924
BSScore: 0.2424

 23%|██▎       | 23/100 [17:58<59:34, 46.42s/it]

Epoch 23/100 | LR: 0.0008751
Train Loss: 0.6218 | Val Loss: 0.4695
IoU per class [0,1,2,3]: [0.9467 0.2241 0.4169 0.6514]
F1 per class [0,1,2,3]:  [0.9726 0.3661 0.5885 0.7889]
IoU burn: 0.5520 | F1 burn: 0.7113
mIoU all: 0.5598 | mIoU severity [1-3]: 0.4308
Burn fraction: pred=0.0808, true=0.0924
BSScore: 0.3224

 24%|██▍       | 24/100 [18:45<59:00, 46.59s/it]

Epoch 24/100 | LR: 0.0008645
Train Loss: 0.6800 | Val Loss: 0.5883
IoU per class [0,1,2,3]: [0.9277 0.1029 0.402  0.6679]
F1 per class [0,1,2,3]:  [0.9625 0.1866 0.5735 0.8009]
IoU burn: 0.4984 | F1 burn: 0.6652
mIoU all: 0.5251 | mIoU severity [1-3]: 0.3910
Burn fraction: pred=0.1090, true=0.0924
BSScore: 0.2917

 25%|██▌       | 25/100 [19:37<1:00:15, 48.20s/it]

Epoch 25/100 | LR: 0.0008536
Train Loss: 0.6043 | Val Loss: 0.4511
IoU per class [0,1,2,3]: [0.9429 0.1429 0.3771 0.6039]
F1 per class [0,1,2,3]:  [0.9706 0.2501 0.5477 0.7531]
IoU burn: 0.4950 | F1 burn: 0.6622
mIoU all: 0.5167 | mIoU severity [1-3]: 0.3746
Burn fraction: pred=0.0676, true=0.0924
BSScore: 0.2856

 26%|██▌       | 26/100 [20:29<1:00:52, 49.36s/it]

Epoch 26/100 | LR: 0.0008423
Train Loss: 0.6783 | Val Loss: 0.4318
IoU per class [0,1,2,3]: [0.9418 0.1215 0.324  0.654 ]
F1 per class [0,1,2,3]:  [0.97   0.2166 0.4894 0.7908]
IoU burn: 0.4855 | F1 burn: 0.6537
mIoU all: 0.5103 | mIoU severity [1-3]: 0.3665
Burn fraction: pred=0.0669, true=0.0924
BSScore: 0.2799

 27%|██▋       | 27/100 [21:22<1:01:23, 50.47s/it]

Epoch 27/100 | LR: 0.0008307
Train Loss: 0.6635 | Val Loss: 0.5177
IoU per class [0,1,2,3]: [0.936  0.0254 0.2288 0.5049]
F1 per class [0,1,2,3]:  [0.967  0.0495 0.3724 0.671 ]
IoU burn: 0.3480 | F1 burn: 0.5163
mIoU all: 0.4238 | mIoU severity [1-3]: 0.2530
Burn fraction: pred=0.0355, true=0.0924
BSScore: 0.1977

 28%|██▊       | 28/100 [22:16<1:01:58, 51.65s/it]

Epoch 28/100 | LR: 0.0008187
Train Loss: 0.6181 | Val Loss: 0.4580
IoU per class [0,1,2,3]: [0.947  0.1681 0.4138 0.6195]
F1 per class [0,1,2,3]:  [0.9728 0.2879 0.5854 0.7651]
IoU burn: 0.5440 | F1 burn: 0.7046
mIoU all: 0.5371 | mIoU severity [1-3]: 0.4005
Burn fraction: pred=0.0764, true=0.0924
BSScore: 0.3105

 29%|██▉       | 29/100 [23:10<1:01:41, 52.14s/it]

Epoch 29/100 | LR: 0.0008065
Train Loss: 0.6160 | Val Loss: 0.4563
IoU per class [0,1,2,3]: [0.9414 0.1676 0.3483 0.6336]
F1 per class [0,1,2,3]:  [0.9698 0.2871 0.5166 0.7757]
IoU burn: 0.4764 | F1 burn: 0.6454
mIoU all: 0.5227 | mIoU severity [1-3]: 0.3831
Burn fraction: pred=0.0645, true=0.0924
BSScore: 0.2817

 30%|███       | 30/100 [23:59<59:41, 51.16s/it]

Epoch 30/100 | LR: 0.0007939
Train Loss: 0.6317 | Val Loss: 0.4735
IoU per class [0,1,2,3]: [0.9383 0.0935 0.3027 0.5769]
F1 per class [0,1,2,3]:  [0.9682 0.1711 0.4647 0.7317]
IoU burn: 0.4025 | F1 burn: 0.5740
mIoU all: 0.4778 | mIoU severity [1-3]: 0.3244
Burn fraction: pred=0.0467, true=0.0924
BSScore: 0.2382

 31%|███       | 31/100 [24:45<57:10, 49.72s/it]

Epoch 31/100 | LR: 0.0007810
Train Loss: 0.6005 | Val Loss: 0.4640
IoU per class [0,1,2,3]: [0.9446 0.0815 0.3132 0.557 ]
F1 per class [0,1,2,3]:  [0.9715 0.1507 0.477  0.7155]
IoU burn: 0.4681 | F1 burn: 0.6377
mIoU all: 0.4741 | mIoU severity [1-3]: 0.3173
Burn fraction: pred=0.0535, true=0.0924
BSScore: 0.2590

 32%|███▏      | 32/100 [25:31<55:03, 48.58s/it]

Epoch 32/100 | LR: 0.0007679
Train Loss: 0.6015 | Val Loss: 0.4361
IoU per class [0,1,2,3]: [0.9423 0.1766 0.3435 0.6274]
F1 per class [0,1,2,3]:  [0.9703 0.3002 0.5113 0.771 ]
IoU burn: 0.4782 | F1 burn: 0.6470
mIoU all: 0.5224 | mIoU severity [1-3]: 0.3825
Burn fraction: pred=0.0629, true=0.0924
BSScore: 0.2821

 33%|███▎      | 33/100 [26:17<53:26, 47.86s/it]

Epoch 33/100 | LR: 0.0007545
Train Loss: 0.6636 | Val Loss: 0.4670
IoU per class [0,1,2,3]: [0.9397 0.118  0.3802 0.3873]
F1 per class [0,1,2,3]:  [0.9689 0.2111 0.551  0.5584]
IoU burn: 0.4451 | F1 burn: 0.6160
mIoU all: 0.4563 | mIoU severity [1-3]: 0.2952
Burn fraction: pred=0.0575, true=0.0924
BSScore: 0.2443

 34%|███▍      | 34/100 [27:03<51:59, 47.27s/it]

Epoch 34/100 | LR: 0.0007409
Train Loss: 0.6104 | Val Loss: 0.4204
IoU per class [0,1,2,3]: [0.9432 0.1449 0.38   0.6713]
F1 per class [0,1,2,3]:  [0.9708 0.2532 0.5508 0.8033]
IoU burn: 0.4806 | F1 burn: 0.6492
mIoU all: 0.5349 | mIoU severity [1-3]: 0.3988
Burn fraction: pred=0.0614, true=0.0924
BSScore: 0.2879

 35%|███▌      | 35/100 [27:49<50:49, 46.91s/it]

Epoch 35/100 | LR: 0.0007270
Train Loss: 0.5949 | Val Loss: 0.4614
IoU per class [0,1,2,3]: [0.9377 0.1802 0.3405 0.6356]
F1 per class [0,1,2,3]:  [0.9678 0.3053 0.508  0.7772]
IoU burn: 0.4371 | F1 burn: 0.6083
mIoU all: 0.5235 | mIoU severity [1-3]: 0.3854
Burn fraction: pred=0.0594, true=0.0924
BSScore: 0.2686

 36%|███▌      | 36/100 [28:35<49:43, 46.61s/it]

Epoch 36/100 | LR: 0.0007129
Train Loss: 0.5492 | Val Loss: 0.4269
IoU per class [0,1,2,3]: [0.9462 0.0941 0.3797 0.5614]
F1 per class [0,1,2,3]:  [0.9724 0.1719 0.5504 0.7191]
IoU burn: 0.4859 | F1 burn: 0.6540
mIoU all: 0.4953 | mIoU severity [1-3]: 0.3450
Burn fraction: pred=0.0556, true=0.0924
BSScore: 0.2736

 37%|███▋      | 37/100 [29:21<48:46, 46.46s/it]

Epoch 37/100 | LR: 0.0006986
Train Loss: 0.6510 | Val Loss: 0.4074
IoU per class [0,1,2,3]: [0.9493 0.1389 0.4252 0.6885]
F1 per class [0,1,2,3]:  [0.974  0.244  0.5967 0.8155]
IoU burn: 0.5266 | F1 burn: 0.6899
mIoU all: 0.5505 | mIoU severity [1-3]: 0.4175
Burn fraction: pred=0.0625, true=0.0924
BSScore: 0.3096

 38%|███▊      | 38/100 [30:07<47:54, 46.36s/it]

Epoch 38/100 | LR: 0.0006841
Train Loss: 0.6008 | Val Loss: 0.4154
IoU per class [0,1,2,3]: [0.947  0.119  0.3939 0.7281]
F1 per class [0,1,2,3]:  [0.9728 0.2126 0.5652 0.8426]
IoU burn: 0.5224 | F1 burn: 0.6863
mIoU all: 0.5470 | mIoU severity [1-3]: 0.4137
Burn fraction: pred=0.0674, true=0.0924
BSScore: 0.3070

 39%|███▉      | 39/100 [30:53<47:00, 46.24s/it]

Epoch 39/100 | LR: 0.0006694
Train Loss: 0.5771 | Val Loss: 0.4973
IoU per class [0,1,2,3]: [0.9322 0.0334 0.2486 0.4956]
F1 per class [0,1,2,3]:  [0.9649 0.0646 0.3982 0.6628]
IoU burn: 0.3189 | F1 burn: 0.4836
mIoU all: 0.4275 | mIoU severity [1-3]: 0.2592
Burn fraction: pred=0.0348, true=0.0924
BSScore: 0.1894

Epoch 40/100 | LR: 0.0006545
Train Loss: 0.5249 | Val Loss: 0.4614
IoU per class [0,1,2,3]: [0.9498 0.2039 0.4199 0.6429]
F1 per class [0,1,2,3]:  [0.9742 0.3388 0.5915 0.7826]
IoU burn: 0.5710 | F1 burn: 0.7269
mIoU all: 0.5541 | mIoU severity [1-3]: 0.4222
Burn fraction: pred=0.0800, true=0.0924
BSScore: 0.3265

 40%|████      | 40/100 [31:39<46:15, 46.27s/it]

Checkpoint saved: BSScore=0.3265 | IoU_burn=0.5710 | mIoU_severity=0.4222

 41%|████      | 41/100 [32:25<45:25, 46.20s/it]

Epoch 41/100 | LR: 0.0006395
Train Loss: 0.5456 | Val Loss: 0.4243
IoU per class [0,1,2,3]: [0.9467 0.1758 0.3704 0.6885]
F1 per class [0,1,2,3]:  [0.9726 0.2991 0.5406 0.8155]
IoU burn: 0.5383 | F1 burn: 0.6998
mIoU all: 0.5454 | mIoU severity [1-3]: 0.4116
Burn fraction: pred=0.0747, true=0.0924
BSScore: 0.3119

 42%|████▏     | 42/100 [33:12<44:37, 46.16s/it]

Epoch 42/100 | LR: 0.0006243
Train Loss: 0.5895 | Val Loss: 0.4208
IoU per class [0,1,2,3]: [0.9458 0.1259 0.3801 0.6879]
F1 per class [0,1,2,3]:  [0.9722 0.2236 0.5509 0.8151]
IoU burn: 0.4948 | F1 burn: 0.6620
mIoU all: 0.5349 | mIoU severity [1-3]: 0.3980
Burn fraction: pred=0.0599, true=0.0924
BSScore: 0.2926

Epoch 43/100 | LR: 0.0006091
Train Loss: 0.5542 | Val Loss: 0.4250
IoU per class [0,1,2,3]: [0.9501 0.1717 0.4335 0.6984]
F1 per class [0,1,2,3]:  [0.9744 0.2931 0.6048 0.8224]
IoU burn: 0.5617 | F1 burn: 0.7193
mIoU all: 0.5634 | mIoU severity [1-3]: 0.4345
Burn fraction: pred=0.0748, true=0.0924
BSScore: 0.3269

 43%|████▎     | 43/100 [33:58<43:55, 46.23s/it]

Checkpoint saved: BSScore=0.3269 | IoU_burn=0.5617 | mIoU_severity=0.4345

 44%|████▍     | 44/100 [34:44<43:01, 46.11s/it]

Epoch 44/100 | LR: 0.0005937
Train Loss: 0.5437 | Val Loss: 0.4294
IoU per class [0,1,2,3]: [0.9393 0.1414 0.3046 0.5946]
F1 per class [0,1,2,3]:  [0.9687 0.2477 0.4669 0.7457]
IoU burn: 0.4220 | F1 burn: 0.5935
mIoU all: 0.4949 | mIoU severity [1-3]: 0.3468
Burn fraction: pred=0.0507, true=0.0924
BSScore: 0.2518

Epoch 45/100 | LR: 0.0005782
Train Loss: 0.5232 | Val Loss: 0.4014
IoU per class [0,1,2,3]: [0.9494 0.2091 0.4411 0.6842]
F1 per class [0,1,2,3]:  [0.9741 0.3459 0.6122 0.8125]
IoU burn: 0.5548 | F1 burn: 0.7137
mIoU all: 0.5710 | mIoU severity [1-3]: 0.4448
Burn fraction: pred=0.0738, true=0.0924
BSScore: 0.3276

 45%|████▌     | 45/100 [35:30<42:15, 46.10s/it]

Checkpoint saved: BSScore=0.3276 | IoU_burn=0.5548 | mIoU_severity=0.4448

 46%|████▌     | 46/100 [36:16<41:31, 46.14s/it]

Epoch 46/100 | LR: 0.0005627
Train Loss: 0.4997 | Val Loss: 0.4267
IoU per class [0,1,2,3]: [0.9436 0.146  0.3691 0.6573]
F1 per class [0,1,2,3]:  [0.971  0.2548 0.5392 0.7932]
IoU burn: 0.4813 | F1 burn: 0.6499
mIoU all: 0.5290 | mIoU severity [1-3]: 0.3908
Burn fraction: pred=0.0608, true=0.0924
BSScore: 0.2857

 47%|████▋     | 47/100 [37:02<40:43, 46.10s/it]

Epoch 47/100 | LR: 0.0005471
Train Loss: 0.5076 | Val Loss: 0.4493
IoU per class [0,1,2,3]: [0.9459 0.2394 0.4419 0.6379]
F1 per class [0,1,2,3]:  [0.9722 0.3863 0.6129 0.7789]
IoU burn: 0.5371 | F1 burn: 0.6988
mIoU all: 0.5663 | mIoU severity [1-3]: 0.4397
Burn fraction: pred=0.0767, true=0.0924
BSScore: 0.3199

 48%|████▊     | 48/100 [37:48<39:57, 46.10s/it]

Epoch 48/100 | LR: 0.0005314
Train Loss: 0.5335 | Val Loss: 0.4310
IoU per class [0,1,2,3]: [0.9446 0.2137 0.4212 0.6977]
F1 per class [0,1,2,3]:  [0.9715 0.3521 0.5928 0.8219]
IoU burn: 0.5198 | F1 burn: 0.6840
mIoU all: 0.5693 | mIoU severity [1-3]: 0.4442
Burn fraction: pred=0.0729, true=0.0924
BSScore: 0.3152

 49%|████▉     | 49/100 [38:34<39:12, 46.12s/it]

Epoch 49/100 | LR: 0.0005157
Train Loss: 0.5089 | Val Loss: 0.4005
IoU per class [0,1,2,3]: [0.9461 0.2147 0.4129 0.7243]
F1 per class [0,1,2,3]:  [0.9723 0.3536 0.5845 0.8401]
IoU burn: 0.5323 | F1 burn: 0.6948
mIoU all: 0.5745 | mIoU severity [1-3]: 0.4506
Burn fraction: pred=0.0741, true=0.0924
BSScore: 0.3215

Epoch 50/100 | LR: 0.0005000
Train Loss: 0.5043 | Val Loss: 0.4085
IoU per class [0,1,2,3]: [0.9509 0.1957 0.3984 0.6809]
F1 per class [0,1,2,3]:  [0.9748 0.3273 0.5698 0.8101]
IoU burn: 0.5835 | F1 burn: 0.7370
mIoU all: 0.5565 | mIoU severity [1-3]: 0.4250
Burn fraction: pred=0.0822, true=0.0924
BSScore: 0.3317

 50%|█████     | 50/100 [39:21<38:31, 46.22s/it]

Checkpoint saved: BSScore=0.3317 | IoU_burn=0.5835 | mIoU_severity=0.4250

Epoch 51/100 | LR: 0.0004843
Train Loss: 0.4678 | Val Loss: 0.4101
IoU per class [0,1,2,3]: [0.9521 0.2002 0.4642 0.7325]
F1 per class [0,1,2,3]:  [0.9755 0.3335 0.6341 0.8456]
IoU burn: 0.5775 | F1 burn: 0.7322
mIoU all: 0.5873 | mIoU severity [1-3]: 0.4656
Burn fraction: pred=0.0754, true=0.0924
BSScore: 0.3418

 51%|█████     | 51/100 [40:07<37:46, 46.26s/it]

Checkpoint saved: BSScore=0.3418 | IoU_burn=0.5775 | mIoU_severity=0.4656

 52%|█████▏    | 52/100 [40:53<36:57, 46.19s/it]

Epoch 52/100 | LR: 0.0004686
Train Loss: 0.5178 | Val Loss: 0.4120
IoU per class [0,1,2,3]: [0.9451 0.1566 0.3882 0.6636]
F1 per class [0,1,2,3]:  [0.9718 0.2707 0.5593 0.7978]
IoU burn: 0.4930 | F1 burn: 0.6604
mIoU all: 0.5384 | mIoU severity [1-3]: 0.4028
Burn fraction: pred=0.0610, true=0.0924
BSScore: 0.2934

Epoch 53/100 | LR: 0.0004529
Train Loss: 0.4994 | Val Loss: 0.4379
IoU per class [0,1,2,3]: [0.951  0.2028 0.4547 0.734 ]
F1 per class [0,1,2,3]:  [0.9749 0.3372 0.6251 0.8466]
IoU burn: 0.5839 | F1 burn: 0.7373
mIoU all: 0.5856 | mIoU severity [1-3]: 0.4638
Burn fraction: pred=0.0820, true=0.0924
BSScore: 0.3435

 53%|█████▎    | 53/100 [41:44<37:17, 47.60s/it]

Checkpoint saved: BSScore=0.3435 | IoU_burn=0.5839 | mIoU_severity=0.4638

 54%|█████▍    | 54/100 [42:31<36:19, 47.37s/it]

Epoch 54/100 | LR: 0.0004373
Train Loss: 0.4831 | Val Loss: 0.4106
IoU per class [0,1,2,3]: [0.947  0.1888 0.4412 0.7036]
F1 per class [0,1,2,3]:  [0.9728 0.3176 0.6123 0.826 ]
IoU burn: 0.5289 | F1 burn: 0.6919
mIoU all: 0.5701 | mIoU severity [1-3]: 0.4445
Burn fraction: pred=0.0701, true=0.0924
BSScore: 0.3185

 55%|█████▌    | 55/100 [43:17<35:19, 47.09s/it]

Epoch 55/100 | LR: 0.0004218
Train Loss: 0.4651 | Val Loss: 0.3922
IoU per class [0,1,2,3]: [0.9487 0.2176 0.4394 0.6656]
F1 per class [0,1,2,3]:  [0.9737 0.3574 0.6106 0.7993]
IoU burn: 0.5448 | F1 burn: 0.7053
mIoU all: 0.5678 | mIoU severity [1-3]: 0.4409
Burn fraction: pred=0.0716, true=0.0924
BSScore: 0.3230

 56%|█████▌    | 56/100 [44:03<34:18, 46.78s/it]

Epoch 56/100 | LR: 0.0004063
Train Loss: 0.4743 | Val Loss: 0.4072
IoU per class [0,1,2,3]: [0.9483 0.2228 0.4092 0.7074]
F1 per class [0,1,2,3]:  [0.9734 0.3644 0.5808 0.8286]
IoU burn: 0.5352 | F1 burn: 0.6973
mIoU all: 0.5719 | mIoU severity [1-3]: 0.4465
Burn fraction: pred=0.0689, true=0.0924
BSScore: 0.3213

 57%|█████▋    | 57/100 [44:49<33:19, 46.51s/it]

Epoch 57/100 | LR: 0.0003909
Train Loss: 0.4918 | Val Loss: 0.4271
IoU per class [0,1,2,3]: [0.9441 0.1133 0.3706 0.6591]
F1 per class [0,1,2,3]:  [0.9713 0.2035 0.5408 0.7945]
IoU burn: 0.4636 | F1 burn: 0.6335
mIoU all: 0.5218 | mIoU severity [1-3]: 0.3810
Burn fraction: pred=0.0530, true=0.0924
BSScore: 0.2765

 58%|█████▊    | 58/100 [45:35<32:25, 46.31s/it]

Epoch 58/100 | LR: 0.0003757
Train Loss: 0.4871 | Val Loss: 0.5451
IoU per class [0,1,2,3]: [0.9192 0.2009 0.4142 0.587 ]
F1 per class [0,1,2,3]:  [0.9579 0.3346 0.5858 0.7397]
IoU burn: 0.4640 | F1 burn: 0.6339
mIoU all: 0.5303 | mIoU severity [1-3]: 0.4007
Burn fraction: pred=0.1139, true=0.0924
BSScore: 0.2826

 59%|█████▉    | 59/100 [46:21<31:33, 46.18s/it]

Epoch 59/100 | LR: 0.0003605
Train Loss: 0.4734 | Val Loss: 0.5012
IoU per class [0,1,2,3]: [0.9326 0.1179 0.2284 0.5214]
F1 per class [0,1,2,3]:  [0.9651 0.2109 0.3718 0.6854]
IoU burn: 0.3358 | F1 burn: 0.5028
mIoU all: 0.4501 | mIoU severity [1-3]: 0.2892
Burn fraction: pred=0.0386, true=0.0924
BSScore: 0.2043

Epoch 60/100 | LR: 0.0003455
Train Loss: 0.4844 | Val Loss: 0.4021
IoU per class [0,1,2,3]: [0.9517 0.2269 0.4887 0.7465]
F1 per class [0,1,2,3]:  [0.9753 0.3699 0.6566 0.8549]
IoU burn: 0.5862 | F1 burn: 0.7391
mIoU all: 0.6035 | mIoU severity [1-3]: 0.4874
Burn fraction: pred=0.0809, true=0.0924
BSScore: 0.3514

 60%|██████    | 60/100 [47:07<30:47, 46.18s/it]

Checkpoint saved: BSScore=0.3514 | IoU_burn=0.5862 | mIoU_severity=0.4874

 61%|██████    | 61/100 [47:53<29:58, 46.12s/it]

Epoch 61/100 | LR: 0.0003306
Train Loss: 0.4357 | Val Loss: 0.4228
IoU per class [0,1,2,3]: [0.9424 0.1586 0.3806 0.6437]
F1 per class [0,1,2,3]:  [0.9704 0.2738 0.5513 0.7833]
IoU burn: 0.4735 | F1 burn: 0.6427
mIoU all: 0.5313 | mIoU severity [1-3]: 0.3943
Burn fraction: pred=0.0608, true=0.0924
BSScore: 0.2840

 62%|██████▏   | 62/100 [48:39<29:10, 46.06s/it]

Epoch 62/100 | LR: 0.0003159
Train Loss: 0.4833 | Val Loss: 0.4246
IoU per class [0,1,2,3]: [0.9415 0.1378 0.3298 0.6702]
F1 per class [0,1,2,3]:  [0.9699 0.2423 0.496  0.8025]
IoU burn: 0.4562 | F1 burn: 0.6265
mIoU all: 0.5198 | mIoU severity [1-3]: 0.3793
Burn fraction: pred=0.0569, true=0.0924
BSScore: 0.2734

 63%|██████▎   | 63/100 [49:25<28:22, 46.02s/it]

Epoch 63/100 | LR: 0.0003014
Train Loss: 0.4914 | Val Loss: 0.4429
IoU per class [0,1,2,3]: [0.9443 0.2283 0.4099 0.714 ]
F1 per class [0,1,2,3]:  [0.9714 0.3718 0.5815 0.8331]
IoU burn: 0.5453 | F1 burn: 0.7058
mIoU all: 0.5741 | mIoU severity [1-3]: 0.4507
Burn fraction: pred=0.0851, true=0.0924
BSScore: 0.3261

 64%|██████▍   | 64/100 [50:11<27:36, 46.01s/it]

Epoch 64/100 | LR: 0.0002871
Train Loss: 0.4791 | Val Loss: 0.4137
IoU per class [0,1,2,3]: [0.948  0.2309 0.417  0.7189]
F1 per class [0,1,2,3]:  [0.9733 0.3752 0.5886 0.8365]
IoU burn: 0.5455 | F1 burn: 0.7059
mIoU all: 0.5787 | mIoU severity [1-3]: 0.4556
Burn fraction: pred=0.0740, true=0.0924
BSScore: 0.3276

 65%|██████▌   | 65/100 [50:57<26:50, 46.01s/it]

Epoch 65/100 | LR: 0.0002730
Train Loss: 0.4232 | Val Loss: 0.4387
IoU per class [0,1,2,3]: [0.9456 0.2094 0.3981 0.7062]
F1 per class [0,1,2,3]:  [0.9721 0.3463 0.5695 0.8278]
IoU burn: 0.5251 | F1 burn: 0.6886
mIoU all: 0.5648 | mIoU severity [1-3]: 0.4379
Burn fraction: pred=0.0724, true=0.0924
BSScore: 0.3152

 66%|██████▌   | 66/100 [51:43<26:03, 45.99s/it]

Epoch 66/100 | LR: 0.0002591
Train Loss: 0.4438 | Val Loss: 0.4390
IoU per class [0,1,2,3]: [0.9449 0.1833 0.4052 0.6663]
F1 per class [0,1,2,3]:  [0.9717 0.3099 0.5768 0.7997]
IoU burn: 0.5033 | F1 burn: 0.6696
mIoU all: 0.5499 | mIoU severity [1-3]: 0.4183
Burn fraction: pred=0.0656, true=0.0924
BSScore: 0.3016

 67%|██████▋   | 67/100 [52:29<25:19, 46.03s/it]

Epoch 67/100 | LR: 0.0002455
Train Loss: 0.4039 | Val Loss: 0.4385
IoU per class [0,1,2,3]: [0.9444 0.2224 0.3922 0.6724]
F1 per class [0,1,2,3]:  [0.9714 0.3639 0.5634 0.8041]
IoU burn: 0.5082 | F1 burn: 0.6739
mIoU all: 0.5578 | mIoU severity [1-3]: 0.4290
Burn fraction: pred=0.0689, true=0.0924
BSScore: 0.3066

 68%|██████▊   | 68/100 [53:15<24:31, 45.97s/it]

Epoch 68/100 | LR: 0.0002321
Train Loss: 0.4582 | Val Loss: 0.4495
IoU per class [0,1,2,3]: [0.9435 0.1437 0.3672 0.6122]
F1 per class [0,1,2,3]:  [0.9709 0.2513 0.5372 0.7595]
IoU burn: 0.4796 | F1 burn: 0.6483
mIoU all: 0.5167 | mIoU severity [1-3]: 0.3744
Burn fraction: pred=0.0604, true=0.0924
BSScore: 0.2802

 69%|██████▉   | 69/100 [54:01<23:46, 46.01s/it]

Epoch 69/100 | LR: 0.0002190
Train Loss: 0.4213 | Val Loss: 0.4385
IoU per class [0,1,2,3]: [0.9454 0.2196 0.3989 0.6737]
F1 per class [0,1,2,3]:  [0.9719 0.3601 0.5703 0.8051]
IoU burn: 0.5155 | F1 burn: 0.6803
mIoU all: 0.5594 | mIoU severity [1-3]: 0.4307
Burn fraction: pred=0.0690, true=0.0924
BSScore: 0.3096

 70%|███████   | 70/100 [54:47<23:00, 46.02s/it]

Epoch 70/100 | LR: 0.0002061
Train Loss: 0.4184 | Val Loss: 0.4586
IoU per class [0,1,2,3]: [0.9431 0.2582 0.4005 0.6251]
F1 per class [0,1,2,3]:  [0.9707 0.4105 0.572  0.7693]
IoU burn: 0.5150 | F1 burn: 0.6799
mIoU all: 0.5567 | mIoU severity [1-3]: 0.4280
Burn fraction: pred=0.0752, true=0.0924
BSScore: 0.3087

 71%|███████   | 71/100 [55:33<22:14, 46.01s/it]

Epoch 71/100 | LR: 0.0001935
Train Loss: 0.4050 | Val Loss: 0.4314
IoU per class [0,1,2,3]: [0.9467 0.2404 0.4093 0.6751]
F1 per class [0,1,2,3]:  [0.9726 0.3876 0.5809 0.806 ]
IoU burn: 0.5263 | F1 burn: 0.6896
mIoU all: 0.5679 | mIoU severity [1-3]: 0.4416
Burn fraction: pred=0.0697, true=0.0924
BSScore: 0.3167

 72%|███████▏  | 72/100 [56:19<21:29, 46.04s/it]

Epoch 72/100 | LR: 0.0001813
Train Loss: 0.4104 | Val Loss: 0.4273
IoU per class [0,1,2,3]: [0.9458 0.2203 0.4158 0.6448]
F1 per class [0,1,2,3]:  [0.9721 0.3611 0.5873 0.784 ]
IoU burn: 0.5115 | F1 burn: 0.6768
mIoU all: 0.5566 | mIoU severity [1-3]: 0.4269
Burn fraction: pred=0.0664, true=0.0924
BSScore: 0.3071

 73%|███████▎  | 73/100 [57:05<20:41, 45.99s/it]

Epoch 73/100 | LR: 0.0001693
Train Loss: 0.3996 | Val Loss: 0.4487
IoU per class [0,1,2,3]: [0.9416 0.2085 0.3907 0.5962]
F1 per class [0,1,2,3]:  [0.9699 0.3451 0.5619 0.747 ]
IoU burn: 0.4771 | F1 burn: 0.6460
mIoU all: 0.5343 | mIoU severity [1-3]: 0.3985
Burn fraction: pred=0.0643, true=0.0924
BSScore: 0.2865

 74%|███████▍  | 74/100 [57:51<19:55, 45.97s/it]

Epoch 74/100 | LR: 0.0001577
Train Loss: 0.4112 | Val Loss: 0.4080
IoU per class [0,1,2,3]: [0.949  0.2689 0.4587 0.7248]
F1 per class [0,1,2,3]:  [0.9739 0.4239 0.6289 0.8405]
IoU burn: 0.5708 | F1 burn: 0.7268
mIoU all: 0.6004 | mIoU severity [1-3]: 0.4841
Burn fraction: pred=0.0823, true=0.0924
BSScore: 0.3450

 75%|███████▌  | 75/100 [58:37<19:10, 46.01s/it]

Epoch 75/100 | LR: 0.0001464
Train Loss: 0.3958 | Val Loss: 0.4301
IoU per class [0,1,2,3]: [0.9446 0.2442 0.3913 0.6609]
F1 per class [0,1,2,3]:  [0.9715 0.3925 0.5625 0.7959]
IoU burn: 0.5045 | F1 burn: 0.6707
mIoU all: 0.5603 | mIoU severity [1-3]: 0.4322
Burn fraction: pred=0.0670, true=0.0924
BSScore: 0.3062

 76%|███████▌  | 76/100 [59:23<18:25, 46.04s/it]

Epoch 76/100 | LR: 0.0001355
Train Loss: 0.4085 | Val Loss: 0.4385
IoU per class [0,1,2,3]: [0.9453 0.2638 0.4292 0.7123]
F1 per class [0,1,2,3]:  [0.9719 0.4174 0.6007 0.832 ]
IoU burn: 0.5588 | F1 burn: 0.7170
mIoU all: 0.5877 | mIoU severity [1-3]: 0.4684
Burn fraction: pred=0.0883, true=0.0924
BSScore: 0.3361

 77%|███████▋  | 77/100 [1:00:09<17:39, 46.07s/it]

Epoch 77/100 | LR: 0.0001249
Train Loss: 0.4225 | Val Loss: 0.4383
IoU per class [0,1,2,3]: [0.9433 0.1861 0.3484 0.6429]
F1 per class [0,1,2,3]:  [0.9708 0.3137 0.5167 0.7826]
IoU burn: 0.4670 | F1 burn: 0.6367
mIoU all: 0.5301 | mIoU severity [1-3]: 0.3924
Burn fraction: pred=0.0564, true=0.0924
BSScore: 0.2812

 78%|███████▊  | 78/100 [1:00:55<16:53, 46.05s/it]

Epoch 78/100 | LR: 0.0001147
Train Loss: 0.4006 | Val Loss: 0.4214
IoU per class [0,1,2,3]: [0.9473 0.2409 0.4378 0.6882]
F1 per class [0,1,2,3]:  [0.9729 0.3882 0.609  0.8153]
IoU burn: 0.5398 | F1 burn: 0.7011
mIoU all: 0.5785 | mIoU severity [1-3]: 0.4556
Burn fraction: pred=0.0738, true=0.0924
BSScore: 0.3256

 79%|███████▉  | 79/100 [1:01:41<16:07, 46.09s/it]

Epoch 79/100 | LR: 0.0001049
Train Loss: 0.4282 | Val Loss: 0.4100
IoU per class [0,1,2,3]: [0.948  0.2357 0.4258 0.7126]
F1 per class [0,1,2,3]:  [0.9733 0.3815 0.5973 0.8322]
IoU burn: 0.5490 | F1 burn: 0.7088
mIoU all: 0.5805 | mIoU severity [1-3]: 0.4580
Burn fraction: pred=0.0755, true=0.0924
BSScore: 0.3296

 80%|████████  | 80/100 [1:02:28<15:22, 46.11s/it]

Epoch 80/100 | LR: 0.0000955
Train Loss: 0.3819 | Val Loss: 0.4231
IoU per class [0,1,2,3]: [0.947  0.2429 0.4445 0.6939]
F1 per class [0,1,2,3]:  [0.9728 0.3909 0.6155 0.8193]
IoU burn: 0.5454 | F1 burn: 0.7058
mIoU all: 0.5821 | mIoU severity [1-3]: 0.4604
Burn fraction: pred=0.0769, true=0.0924
BSScore: 0.3290

 81%|████████  | 81/100 [1:03:14<14:35, 46.08s/it]

Epoch 81/100 | LR: 0.0000865
Train Loss: 0.4025 | Val Loss: 0.4331
IoU per class [0,1,2,3]: [0.9472 0.2231 0.4252 0.7079]
F1 per class [0,1,2,3]:  [0.9729 0.3648 0.5967 0.829 ]
IoU burn: 0.5339 | F1 burn: 0.6961
mIoU all: 0.5759 | mIoU severity [1-3]: 0.4521
Burn fraction: pred=0.0715, true=0.0924
BSScore: 0.3225

 82%|████████▏ | 82/100 [1:04:00<13:49, 46.07s/it]

Epoch 82/100 | LR: 0.0000778
Train Loss: 0.3864 | Val Loss: 0.4396
IoU per class [0,1,2,3]: [0.9438 0.1842 0.3779 0.6749]
F1 per class [0,1,2,3]:  [0.9711 0.3111 0.5485 0.8059]
IoU burn: 0.4904 | F1 burn: 0.6581
mIoU all: 0.5452 | mIoU severity [1-3]: 0.4123
Burn fraction: pred=0.0635, true=0.0924
BSScore: 0.2953

 83%|████████▎ | 83/100 [1:04:46<13:03, 46.07s/it]

Epoch 83/100 | LR: 0.0000696
Train Loss: 0.3799 | Val Loss: 0.4162
IoU per class [0,1,2,3]: [0.9477 0.2294 0.421  0.7221]
F1 per class [0,1,2,3]:  [0.9731 0.3732 0.5925 0.8386]
IoU burn: 0.5412 | F1 burn: 0.7023
mIoU all: 0.5800 | mIoU severity [1-3]: 0.4575
Burn fraction: pred=0.0732, true=0.0924
BSScore: 0.3267

 84%|████████▍ | 84/100 [1:05:32<12:17, 46.11s/it]

Epoch 84/100 | LR: 0.0000618
Train Loss: 0.3955 | Val Loss: 0.4337
IoU per class [0,1,2,3]: [0.9482 0.2487 0.4123 0.7106]
F1 per class [0,1,2,3]:  [0.9734 0.3983 0.5838 0.8308]
IoU burn: 0.5495 | F1 burn: 0.7093
mIoU all: 0.5799 | mIoU severity [1-3]: 0.4572
Burn fraction: pred=0.0753, true=0.0924
BSScore: 0.3295

 85%|████████▌ | 85/100 [1:06:18<11:31, 46.10s/it]

Epoch 85/100 | LR: 0.0000545
Train Loss: 0.3712 | Val Loss: 0.4179
IoU per class [0,1,2,3]: [0.9479 0.2225 0.4162 0.71  ]
F1 per class [0,1,2,3]:  [0.9733 0.364  0.5878 0.8304]
IoU burn: 0.5374 | F1 burn: 0.6991
mIoU all: 0.5741 | mIoU severity [1-3]: 0.4496
Burn fraction: pred=0.0708, true=0.0924
BSScore: 0.3230

 86%|████████▌ | 86/100 [1:07:04<10:46, 46.16s/it]

Epoch 86/100 | LR: 0.0000476
Train Loss: 0.3984 | Val Loss: 0.4304
IoU per class [0,1,2,3]: [0.9459 0.2346 0.4095 0.6692]
F1 per class [0,1,2,3]:  [0.9722 0.38   0.5811 0.8018]
IoU burn: 0.5257 | F1 burn: 0.6891
mIoU all: 0.5648 | mIoU severity [1-3]: 0.4378
Burn fraction: pred=0.0718, true=0.0924
BSScore: 0.3153

 87%|████████▋ | 87/100 [1:07:50<09:59, 46.15s/it]

Epoch 87/100 | LR: 0.0000411
Train Loss: 0.3529 | Val Loss: 0.4289
IoU per class [0,1,2,3]: [0.9466 0.2196 0.3929 0.6985]
F1 per class [0,1,2,3]:  [0.9726 0.3601 0.5642 0.8225]
IoU burn: 0.5230 | F1 burn: 0.6868
mIoU all: 0.5644 | mIoU severity [1-3]: 0.4370
Burn fraction: pred=0.0688, true=0.0924
BSScore: 0.3142

 88%|████████▊ | 88/100 [1:08:36<09:13, 46.10s/it]

Epoch 88/100 | LR: 0.0000351
Train Loss: 0.4071 | Val Loss: 0.4403
IoU per class [0,1,2,3]: [0.9451 0.2208 0.4024 0.6472]
F1 per class [0,1,2,3]:  [0.9718 0.3617 0.5738 0.7858]
IoU burn: 0.5087 | F1 burn: 0.6744
mIoU all: 0.5539 | mIoU severity [1-3]: 0.4235
Burn fraction: pred=0.0670, true=0.0924
BSScore: 0.3051

 89%|████████▉ | 89/100 [1:09:22<08:26, 46.08s/it]

Epoch 89/100 | LR: 0.0000296
Train Loss: 0.3738 | Val Loss: 0.4339
IoU per class [0,1,2,3]: [0.9462 0.2362 0.4133 0.6806]
F1 per class [0,1,2,3]:  [0.9724 0.3822 0.5849 0.81  ]
IoU burn: 0.5266 | F1 burn: 0.6899
mIoU all: 0.5691 | mIoU severity [1-3]: 0.4434
Burn fraction: pred=0.0714, true=0.0924
BSScore: 0.3173

 90%|█████████ | 90/100 [1:10:08<07:40, 46.02s/it]

Epoch 90/100 | LR: 0.0000245
Train Loss: 0.4054 | Val Loss: 0.4476
IoU per class [0,1,2,3]: [0.9436 0.214  0.3755 0.6529]
F1 per class [0,1,2,3]:  [0.971  0.3525 0.546  0.79  ]
IoU burn: 0.4872 | F1 burn: 0.6552
mIoU all: 0.5465 | mIoU severity [1-3]: 0.4141
Burn fraction: pred=0.0629, true=0.0924
BSScore: 0.2948

 91%|█████████ | 91/100 [1:10:54<06:54, 46.06s/it]

Epoch 91/100 | LR: 0.0000199
Train Loss: 0.3953 | Val Loss: 0.4351
IoU per class [0,1,2,3]: [0.9465 0.2432 0.428  0.6864]
F1 per class [0,1,2,3]:  [0.9725 0.3913 0.5995 0.814 ]
IoU burn: 0.5385 | F1 burn: 0.7000
mIoU all: 0.5760 | mIoU severity [1-3]: 0.4525
Burn fraction: pred=0.0754, true=0.0924
BSScore: 0.3242

 92%|█████████▏| 92/100 [1:11:41<06:08, 46.10s/it]

Epoch 92/100 | LR: 0.0000157
Train Loss: 0.3952 | Val Loss: 0.4260
IoU per class [0,1,2,3]: [0.9473 0.2244 0.4252 0.7052]
F1 per class [0,1,2,3]:  [0.973  0.3666 0.5967 0.8271]
IoU burn: 0.5338 | F1 burn: 0.6961
mIoU all: 0.5755 | mIoU severity [1-3]: 0.4516
Burn fraction: pred=0.0711, true=0.0924
BSScore: 0.3223

 93%|█████████▎| 93/100 [1:12:27<05:22, 46.12s/it]

Epoch 93/100 | LR: 0.0000120
Train Loss: 0.3823 | Val Loss: 0.4212
IoU per class [0,1,2,3]: [0.9478 0.241  0.4296 0.7047]
F1 per class [0,1,2,3]:  [0.9732 0.3885 0.601  0.8268]
IoU burn: 0.5438 | F1 burn: 0.7045
mIoU all: 0.5808 | mIoU severity [1-3]: 0.4584
Burn fraction: pred=0.0739, true=0.0924
BSScore: 0.3278

 94%|█████████▍| 94/100 [1:13:13<04:36, 46.09s/it]

Epoch 94/100 | LR: 0.0000089
Train Loss: 0.3673 | Val Loss: 0.4235
IoU per class [0,1,2,3]: [0.9485 0.2504 0.4333 0.723 ]
F1 per class [0,1,2,3]:  [0.9736 0.4006 0.6046 0.8392]
IoU burn: 0.5567 | F1 burn: 0.7152
mIoU all: 0.5888 | mIoU severity [1-3]: 0.4689
Burn fraction: pred=0.0774, true=0.0924
BSScore: 0.3355

 95%|█████████▌| 95/100 [1:13:59<03:50, 46.08s/it]

Epoch 95/100 | LR: 0.0000062
Train Loss: 0.3943 | Val Loss: 0.4277
IoU per class [0,1,2,3]: [0.9471 0.2254 0.4309 0.6884]
F1 per class [0,1,2,3]:  [0.9728 0.3678 0.6023 0.8154]
IoU burn: 0.5326 | F1 burn: 0.6951
mIoU all: 0.5729 | mIoU severity [1-3]: 0.4482
Burn fraction: pred=0.0713, true=0.0924
BSScore: 0.3209

 96%|█████████▌| 96/100 [1:14:45<03:04, 46.07s/it]

Epoch 96/100 | LR: 0.0000039
Train Loss: 0.3457 | Val Loss: 0.4286
IoU per class [0,1,2,3]: [0.9474 0.2463 0.4221 0.704 ]
F1 per class [0,1,2,3]:  [0.973  0.3953 0.5936 0.8263]
IoU burn: 0.5466 | F1 burn: 0.7069
mIoU all: 0.5799 | mIoU severity [1-3]: 0.4575
Burn fraction: pred=0.0763, true=0.0924
BSScore: 0.3286

 97%|█████████▋| 97/100 [1:15:31<02:18, 46.06s/it]

Epoch 97/100 | LR: 0.0000022
Train Loss: 0.3786 | Val Loss: 0.4221
IoU per class [0,1,2,3]: [0.9484 0.2382 0.434  0.7018]
F1 per class [0,1,2,3]:  [0.9735 0.3848 0.6053 0.8248]
IoU burn: 0.5467 | F1 burn: 0.7069
mIoU all: 0.5806 | mIoU severity [1-3]: 0.4580
Burn fraction: pred=0.0734, true=0.0924
BSScore: 0.3288

 98%|█████████▊| 98/100 [1:16:17<01:32, 46.09s/it]

Epoch 98/100 | LR: 0.0000010
Train Loss: 0.3387 | Val Loss: 0.4220
IoU per class [0,1,2,3]: [0.9471 0.2503 0.4308 0.6987]
F1 per class [0,1,2,3]:  [0.9729 0.4004 0.6021 0.8226]
IoU burn: 0.5421 | F1 burn: 0.7031
mIoU all: 0.5817 | mIoU severity [1-3]: 0.4599
Burn fraction: pred=0.0752, true=0.0924
BSScore: 0.3277

 99%|█████████▉| 99/100 [1:17:03<00:46, 46.10s/it]

Epoch 99/100 | LR: 0.0000002
Train Loss: 0.3686 | Val Loss: 0.4256
IoU per class [0,1,2,3]: [0.9479 0.2518 0.4335 0.7187]
F1 per class [0,1,2,3]:  [0.9732 0.4023 0.6048 0.8363]
IoU burn: 0.5539 | F1 burn: 0.7129
mIoU all: 0.5880 | mIoU severity [1-3]: 0.4680
Burn fraction: pred=0.0782, true=0.0924
BSScore: 0.3343

100%|██████████| 100/100 [1:17:49<00:00, 46.70s/it]

Epoch 100/100 | LR: 0.0000000
Train Loss: 0.3511 | Val Loss: 0.4224
IoU per class [0,1,2,3]: [0.9473 0.2344 0.4206 0.7035]
F1 per class [0,1,2,3]:  [0.9729 0.3798 0.5921 0.826 ]
IoU burn: 0.5347 | F1 burn: 0.6968
mIoU all: 0.5764 | mIoU severity [1-3]: 0.4528
Burn fraction: pred=0.0716, true=0.0924
BSScore: 0.3230

In [5]:
import numpy as np
import rasterio
import glob

def load_mask(path):
    with rasterio.open(path) as src:
        return src.read().astype(np.int64)[0]

def class_distribution(mask_paths, n_classes=4):
    counts = np.zeros(n_classes, dtype=np.int64)
    for p in mask_paths:
        mask = load_mask(p)
        for c in range(n_classes):
            counts[c] += (mask == c).sum()
    return counts

mask_paths = glob.glob("./bs/masks/*.tif")
counts = class_distribution(mask_paths)
shares = counts / counts.sum()

for c in range(len(counts)):
    print(f"class {c}: {counts[c]} px ({shares[c]:.4%})")

class 0: 52811255 px (89.9370%)
class 1: 2362871 px (4.0239%)
class 2: 2192271 px (3.7334%)
class 3: 1353859 px (2.3056%)

In [22]:
def evaluate_model(model, loader, device, num_classes=4, ignore_index=255):
    model.eval()

    total_intersection = torch.zeros(num_classes, device=device)
    total_union = torch.zeros(num_classes, device=device)

    f1_metric = MulticlassF1Score(
        num_classes=num_classes,
        average=None,
        ignore_index=ignore_index,
    ).to(device)

    f1_metric.reset()

    with torch.no_grad():
        for images, masks in loader:
            images = images.to(
                device,
                memory_format=torch.channels_last,
                non_blocking=True,
            )

            masks = masks.to(
                device,
                non_blocking=True,
            )

            with torch.autocast(
                device_type="cuda",
                dtype=amp_dtype,
            ):
                outputs = model(images)

            preds = outputs.argmax(dim=1)

            f1_metric.update(outputs, masks)

            valid = masks != ignore_index

            for c in range(num_classes):
                pred_c = (preds == c) & valid
                target_c = (masks == c) & valid

                total_intersection[c] += (pred_c & target_c).sum()
                total_union[c] += (pred_c | target_c).sum()

    iou_per_class = torch.where(
        total_union > 0,
        total_intersection / total_union,
        torch.full_like(total_union, float("nan")),
    ).cpu().numpy()

    f1_per_class = f1_metric.compute().cpu().numpy()

    return {
        "iou_per_class": iou_per_class,
        "f1_per_class": f1_per_class,
        "miou_all": np.nanmean(iou_per_class),
        "miou_target": np.nanmean(iou_per_class[1:]),
    }
trained_model = AttentionUNet().to(device)
state_dict = torch.load("weighted_comboloss_sampler.pt")
trained_model.load_state_dict(state_dict)
trained_model.eval()
test_metrics = evaluate_model(
    model=trained_model,
    loader=test_loader,
    device=device,
    num_classes=4,
    ignore_index=IGNORE_INDEX,
)

print("Test F1 per class:", np.round(test_metrics["f1_per_class"], 4))
print("Test IoU per class:", np.round(test_metrics["iou_per_class"], 4))
print("Test mIoU all:", round(test_metrics["miou_all"], 4))
print("Test target mIoU:", round(test_metrics["miou_target"], 4))

Test F1 per class: [0.9368 0.3637 0.7188 0.7752]
Test IoU per class: [0.8811 0.2222 0.5611 0.633 ]
Test mIoU all: 0.5743
Test target mIoU: 0.4721

In [107]:
@torch.no_grad()
def get_confusion_matrix(
    model,
    loader,
    device,
    num_classes=4,
    ignore_index=255,
):
    model.eval()

    confusion = torch.zeros(
        num_classes,
        num_classes,
        dtype=torch.int64,
        device=device,
    )

    for images, masks in loader:
        images = images.to(
            device,
            memory_format=torch.channels_last,
            non_blocking=True,
        )

        masks = masks.to(device, non_blocking=True)

        with torch.autocast(
            device_type="cuda",
            dtype=amp_dtype,
        ):
            logits = model(images)

        preds = logits.argmax(dim=1)

        valid = masks != ignore_index

        y_true = masks[valid].long()
        y_pred = preds[valid].long()

        indices = y_true * num_classes + y_pred

        confusion += torch.bincount(
            indices,
            minlength=num_classes * num_classes,
        ).reshape(num_classes, num_classes)

    return confusion.cpu().numpy()

In [108]:
cm = get_confusion_matrix(
    model=model,
    loader=val_loader,
    device=device,
)

print("Confusion matrix:")
print(cm)

Confusion matrix:
[[12747405    70721   100699    34719]
 [  302004   127771    33074      183]
 [  148407    11284   252277    35389]
 [   52805        1    18715   336490]]

In [24]:
for col in ds_metadata.columns:
    col_lower = col.lower()

    if any(
        key in col_lower
        for key in [
            "date",
            "time",
            "year",
            "month",
            "lat",
            "lon",
            "lng",
            "x",
            "y",
            "region",
            "tile",
            "utm",
            "scene",
        ]
    ):
        print(f"\n{'=' * 70}")
        print(f"Column: {col}")
        print(f"dtype: {ds_metadata[col].dtype}")
        print(f"nunique: {ds_metadata[col].nunique(dropna=False)}")
        print(ds_metadata[col].head(10).tolist())

======================================================================
Column: region
dtype: float64
nunique: 1
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

======================================================================
Column: x_min
dtype: float64
nunique: 46
[491520.0, 471040.0, 655360.0, 614400.0, 481280.0, 686080.0, 337920.0, 358400.0, 583680.0, 440320.0]

======================================================================
Column: y_min
dtype: float64
nunique: 57
[5376000.0, 5068800.0, 5396480.0, 5345280.0, 5171200.0, 5099520.0, 5283840.0, 5324800.0, 5253120.0, 5570560.0]

======================================================================
Column: x_max
dtype: float64
nunique: 46
[501760.0, 481280.0, 665600.0, 624640.0, 491520.0, 696320.0, 348160.0, 368640.0, 593920.0, 450560.0]

======================================================================
Column: y_max
dtype: float64
nunique: 57
[5386240.0, 5079040.0, 5406720.0, 5355520.0, 5181440.0, 5109760.0, 5294080.0, 5335040.0, 5263360.0, 5580800.0]

======================================================================
Column: acq_datetime
dtype: float64
nunique: 1
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

======================================================================
Column: date_pre
dtype: str
nunique: 140
['2019-04-18', '2019-06-04', '2019-06-14', '2019-06-16', '2019-07-29', '2019-08-16', '2019-08-26', '2019-08-31', '2019-09-03', '2019-09-05']

======================================================================
Column: date_post
dtype: str
nunique: 141
['2019-04-28', '2019-06-19', '2019-06-26', '2019-06-26', '2019-08-08', '2019-08-31', '2019-09-10', '2019-09-25', '2019-10-13', '2019-09-20']

======================================================================
Column: s1_date_pre
dtype: str
nunique: 134
['2019-04-17', '2019-06-04', '2019-06-16', '2019-06-16', '2019-07-27', '2019-08-14', '2019-08-25', '2019-08-25', '2019-09-01', '2019-08-25']

======================================================================
Column: s1_date_post
dtype: str
nunique: 123
['2019-04-29', '2019-06-21', '2019-06-28', '2019-06-28', '2019-08-15', '2019-09-01', '2019-09-18', '2019-09-30', '2019-10-13', '2019-09-18']

======================================================================
Column: n_fire_px
dtype: float64
nunique: 1
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

======================================================================
Column: sev1_px
dtype: float64
nunique: 224
[11360.0, 40651.0, 8335.0, 18761.0, 19588.0, 61501.0, 13179.0, 4084.0, 16687.0, 2336.0]

======================================================================
Column: sev2_px
dtype: float64
nunique: 222
[10.0, 1699.0, 35772.0, 32880.0, 12764.0, 27250.0, 16040.0, 7426.0, 5764.0, 5933.0]

======================================================================
Column: sev3_px
dtype: float64
nunique: 202
[0.0, 29298.0, 18067.0, 6014.0, 1929.0, 18529.0, 3052.0, 1811.0, 4209.0, 18840.0]

In [25]:
meta_audit = ds_metadata.copy()

meta_audit["date_pre_dt"] = pd.to_datetime(
    meta_audit["date_pre"],
    errors="coerce",
)

meta_audit["date_post_dt"] = pd.to_datetime(
    meta_audit["date_post"],
    errors="coerce",
)

meta_audit["year_post"] = meta_audit["date_post_dt"].dt.year
meta_audit["month_post"] = meta_audit["date_post_dt"].dt.month

meta_audit["burn_px"] = (
    meta_audit["sev1_px"].fillna(0)
    + meta_audit["sev2_px"].fillna(0)
    + meta_audit["sev3_px"].fillna(0)
)

print("Диапазон date_pre:")
print(
    meta_audit["date_pre_dt"].min(),
    "—",
    meta_audit["date_pre_dt"].max(),
)

print("\nДиапазон date_post:")
print(
    meta_audit["date_post_dt"].min(),
    "—",
    meta_audit["date_post_dt"].max(),
)

print("\nСцены по post-fire году:")
display(
    meta_audit.groupby("year_post")
    .agg(
        n_chips=("chip_id", "count"),
        n_unique_x=("x_min", "nunique"),
        n_unique_y=("y_min", "nunique"),
        sev1_pixels=("sev1_px", "sum"),
        sev2_pixels=("sev2_px", "sum"),
        sev3_pixels=("sev3_px", "sum"),
        burn_pixels=("burn_px", "sum"),
    )
    .round(0)
)

print("\nСцены по post-fire году и месяцу:")
display(
    meta_audit.groupby(["year_post", "month_post"])
    .size()
    .reset_index(name="n_chips")
)

Диапазон date_pre:
2019-04-18 00:00:00 — 2024-10-11 00:00:00

Диапазон date_post:
2019-04-28 00:00:00 — 2024-11-02 00:00:00

Сцены по post-fire году:

,n_chips,n_unique_x,n_unique_y,sev1_pixels,sev2_pixels,sev3_pixels,burn_pixels
year_post,,,,,,,
2019,11,11,11,204583.0,164020.0,103448.0,472051.0
2020,71,32,41,788652.0,679671.0,431551.0,1899874.0
2021,11,11,11,175904.0,76155.0,31850.0,283909.0
2022,31,24,24,326753.0,507876.0,248762.0,1083391.0
2023,18,14,15,170624.0,156685.0,95686.0,422995.0
2024,82,33,41,696355.0,607864.0,442562.0,1746781.0

Сцены по post-fire году и месяцу:

    year_post  month_post  n_chips
0        2019           4        1
1        2019           6        3
2        2019           8        2
3        2019           9        4
4        2019          10        1
5        2020           4        4
6        2020           7       14
7        2020           8       16
8        2020           9       14
9        2020          10       21
10       2020          11        2
11       2021           4        5
12       2021           7        2
13       2021           8        3
14       2021           9        1
15       2022           5        1
16       2022           6        1
17       2022           7        5
18       2022           8       15
19       2022           9        7
20       2022          10        1
21       2022          11        1
22       2023           8       10
23       2023           9        1
24       2023          10        7
25       2024           4       11
26       2024           5        2
27       2024           7       14
28       2024           8       12
29       2024           9       24
30       2024          10       18
31       2024          11        1

In [53]:
from collections import defaultdict

def get_landcover_group(land_cover):
    group_idx = np.full(
        land_cover.shape,
        fill_value=4,
        dtype=np.int64,
    )

    group_idx[np.isin(land_cover, [10, 20, 95])] = 0
    group_idx[np.isin(land_cover, [30, 100])] = 1
    group_idx[np.isin(land_cover, [40])] = 2
    group_idx[np.isin(land_cover, [90])] = 3

    return group_idx

def inspect_dnbr_by_landcover(df, max_samples_per_chip=1000, seed=42):
    rng = np.random.default_rng(seed)

    group_names = [
        "forest_shrub",
        "grass_moss",
        "cropland",
        "wetland",
        "other",
    ]

    collected = defaultdict(list)

    for _, row in tqdm(df.iterrows(), total=len(df)):
        chip_id = row["chip_id"]

        s2_pre_raw = load_s2(
            build_path(chip_id, "s2_pre")
        )

        s2_post_raw = load_s2(
            build_path(chip_id, "s2_post")
        )

        aux_raw = load_tif(
            build_path(chip_id, "aux")
        )

        target = load_tif(
            build_path(chip_id, "mask")
        )[0].astype(np.int64)

        idx_nir = S2_BAND_IDX["B8A"]
        idx_swir2 = S2_BAND_IDX["B12"]
        idx_scl = S2_BAND_IDX["SCL"]

        pre_nir = s2_pre_raw[idx_nir] / S2_SCALE
        pre_swir2 = s2_pre_raw[idx_swir2] / S2_SCALE

        post_nir = s2_post_raw[idx_nir] / S2_SCALE
        post_swir2 = s2_post_raw[idx_swir2] / S2_SCALE

        pre_nbr = (
            ( pre_nir - pre_swir2 )
            / ( pre_nir + pre_swir2 + 1e-8 )
        )

        post_nbr = (
            ( post_nir - post_swir2 )
            / ( post_nir + post_swir2 + 1e-8 )
        )

        dnbr = np.clip(
            pre_nbr - post_nbr,
            -1.0,
            1.0,
        )

        scl_pre = s2_pre_raw[idx_scl].round()
        scl_post = s2_post_raw[idx_scl].round()

        valid_scl = build_valid_mask_scl(
            scl_pre,
            scl_post,
        ) > 0.5

        valid_target = (
            ( target >= 0 )
            & ( target < NUM_CLASSES )
        )

        valid = valid_scl & valid_target

        land_cover = aux_raw[2].astype(np.int64)
        group_idx = get_landcover_group(land_cover)

        for group_id, group_name in enumerate(group_names):
            for class_id in range(NUM_CLASSES):
                sample_mask = (
                    valid
                    & ( group_idx == group_id )
                    & ( target == class_id )
                )

                values = dnbr[sample_mask]

                if len(values) == 0:
                    continue

                if len(values) > max_samples_per_chip:
                    selected_idx = rng.choice(
                        len(values),
                        size=max_samples_per_chip,
                        replace=False,
                    )

                    values = values[selected_idx]

                collected[
                    (group_name, class_id)
                ].append(values.astype(np.float32))

    rows = []

    for group_name in group_names:
        for class_id in range(NUM_CLASSES):
            values_list = collected.get(
                (group_name, class_id),
                [],
            )

            if len(values_list) == 0:
                rows.append({
                    "landcover_group": group_name,
                    "target_class": class_id,
                    "n_sampled": 0,
                    "mean_dnbr": np.nan,
                    "p10": np.nan,
                    "p25": np.nan,
                    "p50": np.nan,
                    "p75": np.nan,
                    "p90": np.nan,
                })

                continue

            values = np.concatenate(values_list)

            rows.append({
                "landcover_group": group_name,
                "target_class": class_id,
                "n_sampled": len(values),
                "mean_dnbr": float(np.mean(values)),
                "p10": float(np.percentile(values, 10)),
                "p25": float(np.percentile(values, 25)),
                "p50": float(np.percentile(values, 50)),
                "p75": float(np.percentile(values, 75)),
                "p90": float(np.percentile(values, 90)),
            })

    result = pd.DataFrame(rows)

    return result

dnbr_stats = inspect_dnbr_by_landcover(
    train_temporal_df,
    max_samples_per_chip=1000,
    seed=42,
)

display(
    dnbr_stats.round(4)
)

100%|██████████| 142/142 [00:11<00:00, 11.97it/s]

,landcover_group,target_class,n_sampled,mean_dnbr,p10,p25,p50,p75,p90
0,forest_shrub,0,103502,0.0374,-0.0736,-0.0075,0.0382,0.0863,0.1429
1,forest_shrub,1,29635,0.1775,0.1045,0.1279,0.1681,0.2189,0.2659
2,forest_shrub,2,19248,0.3851,0.2547,0.3038,0.3736,0.4634,0.5394
3,forest_shrub,3,7827,0.6671,0.4953,0.5716,0.6608,0.7617,0.8592
4,grass_moss,0,137000,0.0080,-0.0848,-0.0273,0.0088,0.0459,0.0958
5,grass_moss,1,88714,0.1244,0.0677,0.0817,0.1122,0.1584,0.1939
6,grass_moss,2,72896,0.3022,0.2174,0.2504,0.3005,0.3499,0.3831
7,grass_moss,3,67905,0.5036,0.3939,0.4200,0.4712,0.5585,0.6672
8,cropland,0,122122,0.0171,-0.0979,-0.0325,0.0043,0.0533,0.1617
9,cropland,1,94657,0.1248,0.0756,0.0886,0.1154,0.1498,0.1737
10,cropland,2,91404,0.2786,0.1928,0.2236,0.2777,0.3298,0.3643
11,cropland,3,68740,0.4795,0.3887,0.4105,0.4535,0.5219,0.6143
12,wetland,0,51399,0.0256,-0.0740,-0.0123,0.0294,0.0776,0.1392
13,wetland,1,12462,0.1773,0.0854,0.1084,0.1533,0.2307,0.3035
14,wetland,2,10443,0.4653,0.3414,0.3916,0.4598,0.5300,0.6077
15,wetland,3,8249,0.7561,0.5585,0.6612,0.7676,0.8646,0.9296
16,other,0,82488,0.0152,-0.1126,-0.0359,0.0121,0.0637,0.1364
17,other,1,4196,0.1671,0.0889,0.1202,0.1547,0.2047,0.2610
18,other,2,478,0.3357,0.2130,0.2780,0.3343,0.4033,0.4309
19,other,3,11,0.5778,0.3744,0.4220,0.6516,0.7368,0.7729